In [79]:
import pandas as pd
import math
import requests
from bs4 import BeautifulSoup
import json
import numpy as np
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service

from concurrent.futures import ThreadPoolExecutor
import re
import csv
import time

In [80]:
df = pd.read_csv('Data/yad_2_data.csv')
def algo_accuracy(df):
    df['Accuracy'] = 0
    
    for row in range(df.shape[0]):
        accuracy = 20
        
        if pd.notna(df.at[row, 'Neighborhood']):
            accuracy += 10
            
        if pd.notna(df.at[row, 'Home_number']):
            accuracy += 10
            
        if df.at[row, 'Long'] != 0:
            accuracy += 10
            
        if df.at[row, 'Lat'] != 0:
            accuracy += 10
            
        if df.at[row, 'Size'] != 0 and pd.notna(df.at[row, 'Size']):
            accuracy += 10
            
        if df.at[row, 'Rooms'] != 0 and pd.notna(df.at[row, 'Rooms']):
            accuracy += 10
        
        if pd.notna(df.at[row, 'Floor']):
            accuracy += 10
            
        if pd.notna(df.at[row, 'Floors']):
            accuracy += 10
        
        df.at[row, 'Accuracy'] = accuracy
        
    return df

def drop_rows_with_keyword(df):
    keywords = ['פנטאהוס','בדמי מפתח', 'דמי מפתח', 'משרד', 'לא למגורים','סכסוך',
                'משרדים' ,'אולם','לשימור','דרוש שיפוץ','דרושה שיפוץ','להריסה','דירת פאר','מחולקת']
    df['Text'] = df['Text'].astype(str)

    # Generate the conditions for dropping rows
    conditions = [df['Text'].str.contains(keyword, case=False) for keyword in keywords]
    drop_mask = pd.concat(conditions, axis=1).any(axis=1)

    # Drop the rows that meet any of the conditions
    df = df[~drop_mask]

    return df

df = algo_accuracy(df)
df = drop_rows_with_keyword(df) 
try:
    df = df.drop(['level_0', 'index'], axis=1)
except:
    pass
df.to_csv('Data/yad_2_data.csv' ,index=False )
print(df.shape)

(5778, 39)

In [81]:
def get_gush_chelka_api(address):
    headers = {
        'sec-ch-ua': '"Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"',
        'auth_data': '{"api_token":"03387185-da2d-4cb4-a3c6-2292a3df7915","user_token":"","domain":"www.gov.il","token":"qMZlz1IwqfKc6WhO6qet3OHGjLusa/tBvtVdRBurehytCsrtnVhcI81jhg/2pDc39ChRLpK7C+mzq4rg5GjqdHfTQJANTYMPAmVWrfMwL4O2AMtdLCq+QEt/inww791B+vWYq7Z0PiAq8lUPSBuB1//YGsM/BvB9daJoQwguhya+2NxIm2JK2gfMp+RnSHzGdn4LFWLuLw3lHHYzhGT8Q8+3vzRbF/vSl79P7qNAoLxGPApgGa80OA==","user_id":178592,"isAdmin":false,"expires":"2023-08-15T21:20:19.0844919+03:00"}',
        'sec-ch-ua-mobile': '?0',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
        'Content-Type': 'application/json; charset=UTF-8',
        'Accept': 'application/json, text/javascript, */*; q=0.01',
        'Referer': 'https://www.gov.il/',
        'sec-ch-ua-platform': '"Windows"',
    }

    json_data = {
        'type': 0,
        'address': address,
    }

    response = requests.post('https://ags.govmap.gov.il/Api/Controllers/GovmapApi/SearchAndLocate', headers=headers, json=json_data)
    if response.status_code == 200:
        data = response.json()
        if data['status'] != 0:
            return False
        if 'data' in data and len(data['data']) > 0 and 'Values' in data['data'][0]:
            return [int(value) for value in data['data'][0]['Values']]
    return False

In [82]:
def add_gush_helka_tat(df, city='תל אביב'):
    df.loc[:, 'Gush'] = np.nan
    df.loc[:, 'Helka'] = np.nan
    df.loc[:, 'Tat'] = np.nan

    df1_gov = pd.read_csv("Data/Real_Estate_TLV_GOVMAPS_1.csv", index_col=0)
    df2_gov = pd.read_csv("Data/Real_Estate_TLV_GOVMAPS_2.csv", index_col=0)
    df_gov = pd.merge(df1_gov, df2_gov, how='outer')
    df_gov[['Gush', 'Helka', 'Tat']] = df_gov['GUSHHELKATAT'].str.split('-|/', n=2, expand=True).astype(np.int32)
    df_gov['Home_number'] = df_gov['ADDRESS'].str.extract('(\d+)').astype(np.int32)
    
    # Level 0: Government Maps API
    for index, row in df.iterrows():
        if pd.notna(row['Home_number']):
            home_number = int(row['Home_number'])
            street = row['Street']
            
            for home_n in range(0,8,2):
                home_number = home_number + home_n
                address = str(street)+' '+str(home_number)+' '+city
                gush_chelka = get_gush_chelka_api(address)
                if gush_chelka:
                    df.loc[index, 'Gush'] = gush_chelka[0]
                    df.loc[index, 'Helka'] = gush_chelka[1]
                    break
            
    # Level 1: Government Maps
    for index, row in df.iterrows():
        if pd.notna(row['Home_number']) and pd.isna(row['Gush']):
            home_number = row['Home_number']
            street = row['Street']

            matches = df_gov.loc[
                (df_gov['STREENNAME'].str.contains(street)) & (df_gov['Home_number'] == home_number), ['Gush', 'Helka', 'Tat']]

            if not matches.empty:
                df.loc[index, 'Gush'] = matches['Gush'].values[0]
                df.loc[index, 'Helka'] = matches['Helka'].values[0]
                df.loc[index, 'Tat'] = matches['Tat'].values[0]

    # Level 2: Nadlan Database
    print(df['Gush'].notna().sum())
    df_nadlan = pd.read_csv("Data/Nadlan.csv")
    df_nadlan[['Gush', 'Helka', 'Tat']] = df_nadlan['GUSH'].str.split('-|/', n=2, expand=True).astype(np.int32)
    df_nadlan = df_nadlan.drop(columns='GUSH', axis=1)
    df_nadlan[['Street', 'Home_number']] = df_nadlan['DISPLAYADRESS'].str.extract('(.+)\s+(\d+)')
    df_nadlan.dropna(subset=['Home_number'], inplace=True)
    df_nadlan['Home_number'] = df_nadlan['Home_number'].astype(np.int32)

    for index, row in df.iterrows():
        if pd.notna(row['Home_number']) and pd.isna(row['Gush']):
            home_number = row['Home_number']
            street = row['Street']

            matches = df_nadlan.loc[
                (df_nadlan['Street'].str.contains(street)) & (df_nadlan['Home_number'] == home_number), ['Gush', 'Helka', 'Tat']]

            if not matches.empty:
                df.loc[index, 'Gush'] = matches['Gush'].values[0]
                df.loc[index, 'Helka'] = matches['Helka'].values[0]
                df.loc[index, 'Tat'] = matches['Tat'].values[0]

    # Level 3: Addresses
    print(df['Gush'].notna().sum())
    df_address = pd.read_csv("Data/Addresses.csv")
    for index, row in df.iterrows():
        if pd.notna(row['Home_number']):
            home_number = row['Home_number']
            street = row['Street']

            gush = df_address.loc[(df_address['ms_bayit'] == home_number) & (df_address['t_rechov'].str.contains(street)), 'ms_gush']
            helka = df_address.loc[(df_address['ms_bayit'] == home_number) & (df_address['t_rechov'].str.contains(street)), 'ms_chelka']

            if not gush.empty:
                df.at[index, 'Gush'] = gush.iloc[0]
            if not helka.empty:
                df.at[index, 'Helka'] = helka.iloc[0]

            if gush.empty and helka.empty:
                street_parts = street.split(' ')
                last_part = street_parts[-1]
                matching_streets = df_address[df_address['t_rechov'].str.contains(last_part)]
                if not matching_streets.empty:
                    gush = matching_streets.loc[matching_streets['ms_bayit'] == home_number, 'ms_gush']
                    helka = matching_streets.loc[matching_streets['ms_bayit'] == home_number, 'ms_chelka']
                    if not gush.empty:
                        df.at[index, 'Gush'] = gush.iloc[0]
                    if not helka.empty:
                        df.at[index, 'Helka'] = helka.iloc[0]

    df = df.dropna(subset=['Gush', 'Helka'])
    df.loc[:, 'Gush'] = df['Gush'].astype(np.int32)
    df.loc[:, 'Helka'] = df['Helka'].astype(np.int32)

    print(df['Gush'].notna().sum())
    return df

df = add_gush_helka_tat(df)
print(f'shape {df.shape}')
# shape (1637, 42)

דוד אבידן 17 תל אביב
יוחנן הורקנוס 6 תל אביב
רציף הרברט סמואל 42 תל אביב
לה גווארדיה 38 תל אביב
שקד 48 תל אביב
שיבת ציון 26 תל אביב
אורי צבי גרינברג 9 תל אביב
החשמונאים 96 תל אביב
ליברמן 9 תל אביב
נס הרים 10 תל אביב
נס הרים 12 תל אביב
נס הרים 16 תל אביב
נס הרים 22 תל אביב
רפידים 20 תל אביב
שתולים 48 תל אביב
השלושה 2 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
ד"ר בודנהיימר 8 תל אביב
ד"ר בודנהיימר 10 תל אביב
ד"ר בודנהיימר 14 תל אביב
ד"ר בודנהיימר 20 תל אביב
נהלל 20 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
החלוצים 41 תל אביב
רוטנשטרייך 30 תל אביב
דרך נמיר 85 תל אביב
עין חרוד 9 תל אביב
דרך משה דיין 29 תל אביב
בושם 64 תל אביב
דוד רזיאל 10 תל אביב
שדרות ישראל גורי 4 תל אביב
קורט טוכולסקי 6 תל אביב
דרך משה דיין 24 תל אביב
בן שפרוט 2 תל אביב
ליאונרדו דה וינצ'י 2 תל אביב
ליאונרדו דה וינצ'י 4 תל אביב
ליאונרדו דה וינצ'י 8 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
שבתאי 29 תל אביב
החשמונאים 96 תל אביב
הזוהר 10 תל אביב
מזל דגים 1 תל אביב
מזל דגים 3 תל אביב
מזל דגים 7 תל אביב
מזל דגים 13 תל אביב
שדרות ירושלים 151 תל אביב
המכבי 9 תל אביב
צוקרמן 21 תל אביב
מעפילי אגוז 56 תל אביב
התקומה 19 תל אביב
התקומה 21 תל אביב
התקומה 25 תל אביב
התקומה 31 תל אביב
ישראל גלילי 14 תל אביב
סגולה 11 תל אביב
טשרניחובסקי 8 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
דיק 12 תל אביב
אביגדור סטימצקי 12 תל אביב
משה וילנסקי 45 תל אביב
ירמיהו 14 תל אביב
אלמגור 19 תל אביב
דרך הטייסים 100 תל אביב
דרך הטייסים 102 תל אביב
קורקידי 20 תל אביב
חזנוביץ' 10 תל אביב
חזנוביץ' 12 תל אביב
חזנוביץ' 16 תל אביב
חזנוביץ' 22 תל אביב
החשמונאים 96 תל אביב
שמואל רומנילי 1 תל אביב
קהילת יאסי 13 תל אביב
ריינס 32 תל אביב
בזל 35 תל אביב
ניסים אלוני 19 תל אביב
זמנהוף 40 תל אביב
איינשטיין 10 תל אביב
איינשטיין 12 תל אביב
איינשטיין 16 תל אביב
איינשטיין 22 תל אביב
עזה 52 תל אביב
החשמונאים 100 תל אביב
החשמונאים 96 תל אביב
סוטין 15 תל אביב
הגיבור האלמוני 46 תל אביב
יסוד המעלה 25 תל אביב
מורדי הגטאות 21 תל אביב
שטרוק 7 תל אביב
החשמונאים 100 תל אביב
ניר עם 4 תל אביב
הקישון 79 תל אביב
פרחי אביב 17 תל אביב
החשמונאים 100 תל אביב
פנקס 62 תל אביב
מלצ'ט 64 תל אביב
רבי משה בן עזרא 4 תל אביב
רבי משה בן עזרא 6 תל אביב
רבי משה בן עזרא 10 תל אביב
רבי משה בן עזרא 16 תל אביב
מיכלאנג'לו 33 תל אביב
מיכלאנג'לו 35 תל אביב
מיכלאנג'לו 39 תל אביב
מיכלאנג'לו 45 תל אביב
מח"ל 70 תל אביב
שדרות מוצקין 9 תל אביב
שדרות מוצקין 11 תל אביב
שדרות מוצקין 15 תל אביב
שדרות מוצקין 21 תל אביב
ג'ורג' אליוט 3 תל אביב
חולדה 5 תל אביב
פינסקר 53 תל אביב
שדרות ששת הימים 35 תל אביב
משה וילנסקי 55 תל אביב
שדרות וושינגטון 14 תל אביב
שלמה המלך 88 תל אביב
דרך ההגנה 140 תל אביב
אבן גבירול 58 תל אביב
רמז 36 תל אביב
וינגייט 1 תל אביב
וינגייט 3 תל אביב
וינגייט 7 תל אביב
וינגייט 13 תל אביב
שדרות הבעש"ט 9 תל אביב
דיזנגוף 275 תל אביב
הודיה 14 תל אביב
ישראל גלילי 9 תל אביב
שדרות חכמי ישראל 99 תל אביב
שדרות חכמי ישראל 101 תל אביב
שדרות חכמי ישראל 105 תל אביב
שדרות חכמי ישראל 111 תל אביב
כוכבי יצחק 3 תל אביב
ארלוזורוב 17 תל אביב
ארלוזורוב 19 תל אביב
עמישב 54 תל אביב
אבן גבירול 116 תל אביב
אבן גבירול 118 תל אביב
חניון היכל הספורט יד אליהו 1 תל אביב
חניון היכל הספורט יד אליהו 3 תל אביב
חניון היכל הספורט יד אליהו 7 תל אביב
חניון היכל הספורט יד אליהו 13 תל אביב
משה וילנסקי 31 תל אביב
וינגייט 1 תל אביב
וינגייט 3 תל אביב
וינגייט 7 תל אביב
וינגייט 13 תל אביב
טאגור 39 תל אביב
לה גווארדיה 26 תל אביב
שילה 3 תל אביב
בוגרשוב 70 תל אביב
חברון 12 תל אביב
וולפסון 57 תל אביב
שדרות מוצקין 9 תל אביב
שדרות מוצקין 11 תל אביב
שדרות מוצקין 15 תל אביב
שדרות מוצקין 21 תל אביב
יהודה הימית 2 תל אביב
מנחם ארבר 13 תל אביב
מנחם ארבר 15 תל אביב
שדרות רוטשילד 17 תל אביב
העבודה 4 תל אביב
מזא"ה 62 תל אביב
מזא"ה 64 תל אביב
מזא"ה 68 תל אביב
מזא"ה 74 תל אביב
רמז 6 תל אביב
רציף הרברט סמואל 46 תל אביב
החשמונאים 98 תל אביב
שדרות לוי אשכול 4 תל אביב
שדרות לוי אשכול 6 תל אביב
שדרות לוי אשכול 10 תל אביב
שדרות לוי אשכול 16 תל אביב
דרך השלום 79 תל אביב
שדרות ששת הימים 1 תל אביב
הנביאים 15 תל אביב
יציאת אירופה 17 תל אביב
ראשון לציון 9 תל אביב
ראשון לציון 11 תל אביב
ראשון לציון 15 תל אביב
ראשון לציון 21 תל אביב
שדרות לוי אשכול 36 תל אביב
שדרות לוי אשכול 38 תל אביב
שדרות לוי אשכול 42 תל אביב
שדרות לוי אשכול 48 תל אביב
ניסים אלוני 21 תל אביב
יחזקאל שטרייכמן 12 תל אביב
דיזנגוף 119 תל אביב
כוכבי יצחק 13 תל אביב
צונץ 1 תל אביב
מחרוזת 14 תל אביב
ניסים אלוני 3 תל אביב
מח"ל 78 תל אביב
בית אל 2 תל אביב
אריאל 11 תל אביב
בלפור 8 תל אביב
רציף הרברט סמואל 46 תל אביב
טשרניחובסקי 24 תל אביב
חברה חדשה 4 תל אביב
לה גווארדיה 29 תל אביב
בזל 33 תל אביב
הלפיד 3 תל אביב
זלמן שז"ר 26 תל אביב
חסידי האומות 22 תל אביב
שתולים 57 תל אביב
איינשטיין 9 תל אביב
הרב אלנקווה 40 תל אביב
הרב אלנקווה 42 תל אביב
הרב אלנקווה 46 תל אביב
הרב אלנקווה 52 תל אביב
פיקוס 5 תל אביב
אליהו ברלין 11 תל אביב
הירקון 49 תל אביב
חובבי ציון 51 תל אביב
נווה שאנן 38 תל אביב
לוין קיפניס 1 תל אביב
יהודה הימית 25 תל אביב
דרך מנחם בגין 144 תל אביב
עירית 4 תל אביב
רמז 6 תל אביב
אדר 1 תל אביב
חסידי האומות 22 תל אביב
איסרליש 14 תל אביב
גרציאני יצחק 2 תל אביב
גרציאני יצחק 4 תל אביב
גרציאני יצחק 8 תל אביב
גרציאני יצחק 14 תל אביב
לסר אורי 6 תל אביב
בית פלט 42 תל אביב
בית פלט 44 תל אביב
בית פלט 48 תל אביב
בית פלט 54 תל אביב
משה וילנסקי 6 תל אביב
וייצמן 80 תל אביב
יסוד המעלה 44 תל אביב
יסוד המעלה 46 תל אביב
יסוד המעלה 50 תל אביב
יסוד המעלה 56 תל אביב
רש"י 57 תל אביב
בן שפרוט 2 תל אביב
מרגוע 12 תל אביב
משה קול 1 תל אביב
משה שרת 7 תל אביב
מירון 3 תל אביב
מירון 5 תל אביב
סהרון 18 תל אביב
סוטין 15 תל אביב
תוצרת הארץ 9 תל אביב
זלמן שז"ר 31 תל אביב
גרציאני יצחק 4 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 10 תל אביב
גרציאני יצחק 16 תל אביב
ישראל גלילי 8 תל אביב
בית פלט 22 תל אביב
בית פלט 24 תל אביב
משה שרת 40 תל אביב
הרב יעקב טראב 8 תל אביב
צהלון הרופא 1 תל אביב
צהלון הרופא 3 תל אביב
שדרות מוצקין 9 תל אביב
שדרות מוצקין 11 תל אביב
שדרות מוצקין 15 תל אביב
שדרות מוצקין 21 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
שדרות יהודית 33 תל אביב
הקשת 4 תל אביב
שדרות ששת הימים 1 תל אביב
יהודה הימית 11 תל אביב
יהודה הימית 13 תל אביב
נחלת בנימין 129 תל אביב
קהילת מקסיקו 9 תל אביב
קהילת מקסיקו 11 תל אביב
קהילת מקסיקו 15 תל אביב
קהילת מקסיקו 21 תל אביב
הרב אלנקווה 35 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 8 תל אביב
גרציאני יצחק 12 תל אביב
גרציאני יצחק 18 תל אביב
גאולה 40 תל אביב
גלעינית 5 תל אביב
בארט 19 תל אביב
פיקוס 8 תל אביב
מחרוזת 13 תל אביב
ראשית חכמה 7 תל אביב
בורוכוב 6 תל אביב
בורוכוב 8 תל אביב
בורוכוב 12 תל אביב
לוינסקי 73 תל אביב
לוינסקי 75 תל אביב
לוינסקי 79 תל אביב
ניסים אלוני 21 תל אביב
מטלון 78 תל אביב
מטלון 80 תל אביב
מטלון 84 תל אביב
אילת 61 תל אביב
ניסים אלוני 16 תל אביב
גלעינית 5 תל אביב
משגב עם 4 תל אביב
בר הופמן 5 תל אביב
חיננית 4 תל אביב
שתולים 48 תל אביב
איינשטיין 14 תל אביב
איינשטיין 16 תל אביב
איינשטיין 20 תל אביב
נווה שלום 26 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 16 תל אביב
ליאונרדו דה וינצ'י 20 תל אביב
ליאונרדו דה וינצ'י 26 תל אביב
הרב רובינשטיין 55 תל אביב
הרב רובינשטיין 57 תל אביב
הרב רובינשטיין 61 תל אביב
הרב רובינשטיין 67 תל אביב
אדני פז 44 תל אביב
אדני פז 46 תל אביב
אדני פז 50 תל אביב
אדני פז 56 תל אביב
יהושע בן נון 29 תל אביב
רנ"ק 1 תל אביב
אנסקי 8 תל אביב
העלייה 40 תל אביב
גליקסון 6 תל אביב
י.ל. פרץ 38 תל אביב
י.ל. פרץ 40 תל אביב
י.ל. פרץ 44 תל אביב
י.ל. פרץ 50 תל אביב
קמינסקה 3 תל אביב
השופטים 3 תל אביב
מוסינזון 21 תל אביב
שלום עליכם 22 תל אביב
פין 1 תל אביב
נתן אלבז 1 תל אביב
מעון 5 תל אביב
סמטת נורדאו 7 תל אביב
פנקס 66 תל אביב
דיזנגוף 231 תל אביב
רוחמה 20 תל אביב
אבודרהם 6 תל אביב
קרליבך 4 תל אביב
שתולים 63 תל אביב
יפתח 16 תל אביב
הרב רובינשטיין 19 תל אביב
הרב רובינשטיין 21 תל אביב
הרב רובינשטיין 25 תל אביב
הרב רובינשטיין 31 תל אביב
נגבה 32 תל אביב
בית אל 15 תל אביב
בית אל 17 תל אביב
בית אל 21 תל אביב
בית אל 27 תל אביב
כביר 10 תל אביב
מאיר יערי 28 תל אביב
יהודה הימית 25 תל אביב
החשמונאים 100 תל אביב
דרך ההגנה 60 תל אביב
צונץ 15 תל אביב
בזל 35 תל אביב
שלום עליכם 45 תל אביב
יהודה עמיחי 14 תל אביב
דיזנגוף 190 תל אביב
הקליר 10 תל אביב
שדרות דוד המלך 51 תל אביב
שדרות לוי אשכול 18 תל אביב
שדרות לוי אשכול 20 תל אביב
שדרות לוי אשכול 24 תל אביב
שדרות לוי אשכול 30 תל אביב
קהילת קנדה 15 תל אביב
ניסים אלוני 19 תל אביב
היהודי זיס 21 תל אביב
ענתות 35 תל אביב
יעקב וייס 2 תל אביב
בן יהודה 244 תל אביב

קהילת ברזיל 10 תל אביב
אמיר גלבוע 15 תל אביב
סוטין 15 תל אביב
קהילת פאדובה 30 תל אביב
דרך משה דיין 3 תל אביב
דרך משה דיין 5 תל אביב
דרך משה דיין 9 תל אביב
דרך משה דיין 15 תל אביב
ליאונרדו דה וינצ'י 12 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 18 תל אביב
ליאונרדו דה וינצ'י 24 תל אביב
תרצה 23 תל אביב
בושם 8 תל אביב
החשמונאים 100 תל אביב
ניסים אלוני 5 תל אביב
ליליין 8 תל אביב
הרב יעקב טראב 8 תל אביב
פיארברג 16 תל אביב
פיארברג 18 תל אביב
פיארברג 22 תל אביב
ה' באייר 52 תל אביב
בן יהודה 44 תל אביב
אליעזר קפלן 19 תל אביב
אליעזר קפלן 21 תל אביב
אליעזר קפלן 25 תל אביב
אליעזר קפלן 31 תל אביב
דרך שלמה 1 תל אביב
אהרון בקר 2 תל אביב
ליסין 1 תל אביב
החשמונאים 100 תל אביב
ליאונרדו דה וינצ'י 6 תל אביב
אברהם בויאר 11 תל אביב
אברהם בויאר 13 תל אביב
אברהם בויאר 17 תל אביב
אברהם בויאר 23 תל אביב
יהודה עמיחי 14 תל אביב
ליאונרדו דה וינצ'י 13 תל אביב
שלום עליכם 27 תל אביב
עזה 6 תל אביב
מיכאל נאמן 4 תל אביב
צלילי חנינא 38 תל אביב
יחזקאל שטרייכמן 12 תל אביב
אוריאל אקוסטה 5 תל אביב
דיזנגוף 50 תל אביב
חברון 8 תל אביב
הרטוב 24 תל אביב
שדרות נורדאו 88 תל אביב
לח"י 38 תל אביב
פנקס 66 תל אביב
פנקס 19 תל אביב
יחיאל דב דרזנר 4 תל אביב
משה וילנסקי 29 תל אביב
משה וילנסקי 31 תל אביב
יוחנן הורקנוס 33 תל אביב
אח"י דקר 25 תל אביב
מאוריציו ויטלה 9 תל אביב
בושם 22 תל אביב
משה בריל 5 תל אביב
מבצע קדש 34 תל אביב
רמה 22 תל אביב
בן יהודה 36 תל אביב
גליצנשטיין 7 תל אביב
יפת 169 תל אביב
יפת 171 תל אביב
דרך מנחם בגין 144 תל אביב
יהודה עמיחי 11 תל אביב
ד"ר אברהם אליהו הרכבי 19 תל אביב
ד"ר אברהם אליהו הרכבי 21 תל אביב
ד"ר אברהם אליהו הרכבי 25 תל אביב
ד"ר אברהם אליהו הרכבי 31 תל אביב
סירקין 32 תל אביב
זכריה 30 תל אביב
מזא"ה 5 תל אביב
שדרות רוטשילד 17 תל אביב
בושם 28 תל אביב
בארי 1 תל אביב
דרך מנחם בגין 144 תל אביב
שדרות ששת הימים 10 תל אביב
זלמן שז"ר 24 תל אביב
משה וילנסקי 1 תל אביב
שדרות ההשכלה 17 תל אביב
חסידי האומות 24 תל אביב
קניוק יורם 1 תל אביב
קניוק יורם 3 תל אביב
קניוק יורם 7 תל אביב
קניוק יורם 13 תל אביב
כרם חמד 3 תל אביב
אלנבי 1 תל אביב
עזה 5 תל אביב
נהרדעא 10 תל אביב
ליפסקי 12 תל אביב
שקד 36 תל אביב
רקנאטי 5 תל אביב
רש"י 25 תל אביב
רש"י 27 תל אביב
רש"י 31 תל אביב
רש"י 37 תל אביב
פיקוס 7 תל אביב
וולפסון 55 תל אביב
אנריקה פברגט 4 תל אביב
אנריקה פברגט 6 תל אביב
אנריקה פברגט 10 תל אביב
אנריקה פברגט 16 תל אביב
נדב 49 תל אביב
אייגר 10 תל אביב
בן יהודה 216 תל אביב
ניסים אלוני 4 תל אביב
דרך מנחם בגין 144 תל אביב
דרך הטייסים 114 תל אביב
מודיעין 8 תל אביב
נווה שאנן 23 תל אביב
קהילת קנדה 26 תל אביב
פוריה 1 תל אביב
דרך משה דיין 34 תל אביב
דרך משה דיין 36 תל אביב
דרך משה דיין 40 תל אביב
שדרות מסריק 14 תל אביב
בן שפרוט 15 תל אביב
דרך משה דיין 51 תל אביב
יציאה למחלף גלילות 1 תל אביב
יציאה למחלף גלילות 3 תל אביב
יציאה למחלף גלילות 7 תל אביב
יציאה למחלף גלילות 13 תל אביב
קהילת ורשה 10 תל אביב
החשמונאים 100 תל אביב
ברנשטיין כהן 11 תל אביב
יסוד המעלה 31 תל אביב
הזוהר 5 תל אביב
דיזנגוף 50 תל אביב
מתתיהו 1 תל אביב
זכריה 30 תל אביב
דעואל 12 תל אביב
אפלטון 8 תל אביב
הרב קוק 11 תל אביב
אבן גבירול 149 תל אביב
יפת 171 תל אביב
החשמונאים 96 תל אביב
יחזקאל שטרייכמן 12 תל אביב
הס 5 תל אביב
דיזנגוף 114 תל אביב
אלכסנדר ינאי 14 תל אביב
פתחיה מרגנשבורג 20 תל אביב
הס 27 תל אביב
בנימיני 5 תל אביב
אריה אלטמן 7 תל אביב
אריה אלטמן 9 תל אביב
אריה אלטמן 13 תל אביב
אריה אלטמן 19 תל אביב
שדרות נורדאו 80 תל אביב
ברזיל 2 תל אביב
דרך השלום 92 תל אביב
בית הלל 30 תל אביב
רמה 16 תל אביב
יהודה הנשיא 38 תל אביב
החשמונאים 100 תל אביב
שדרות ששת הימים 5 תל אביב
ויסוצקי 6 תל אביב
דרך מנחם בגין 144 תל אביב
ניסים אלוני 21 תל אביב
דרך שלמה 4 תל אביב
פנקס 6 תל אביב
דרך נמיר 116 תל אביב
קליי 10 תל אביב
קמינסקה 22 תל אביב
עמיחי פאגלין 6 תל אביב
עמיחי פאגלין 8 תל אביב
נווה שאנן 20 תל אביב
דיזנגוף 118 תל אביב
מירון 5 תל אביב
ניסים אלוני 5 תל אביב
פטרסון 5 תל אביב
אברבנאל 49 תל אביב
שדרות ששת הימים 16 תל אביב
מודיליאני 12 תל אביב
יונה הנביא 18 תל אביב
הרצל רוזנבלום 12 תל אביב
קרית ספר 10 תל אביב
קרית ספר 10 תל אביב
יפת 177 תל אביב
בן יהודה 36 תל אביב
דוידקה 1 תל אביב
נרדור 10 תל אביב
הרצל 108 תל אביב
הרב יעקב טראב 8 תל אביב
לוחמי גליפולי 50 תל אביב
מרחביה 17 תל אביב
ניסים אלוני 16 תל אביב
פיקוס 3 תל אביב
ליאונרדו דה וינצ'י 12 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 18 תל אביב
ליאונרדו דה וינצ'י 24 תל אביב
מרסל ינקו 2 תל אביב
חידושי הרי"ם 3 תל אביב
פינלס 10 תל אביב
רודנסקי 8 תל אביב
שקד 19 תל אביב
שתולים 59 תל אביב
ליאונרדו דה וינצ'י 12 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 18 תל אביב
ליאונרדו דה וינצ'י 24 תל אביב
יוניצמן 21 תל אביב
יוניצמן 23 תל אביב
יוניצמן 27 תל אביב
יוניצמן 33 תל אביב
החשמונאים 100 תל אביב
מגדל 1 תל אביב
בורוכוב 6 תל אביב
בורוכוב 8 תל אביב
בורוכוב 12 תל אביב
החשמונאים 100 תל אביב
אח"י דקר 4 תל אביב
אח"י דקר 6 תל אביב
אח"י דקר 10 תל אביב
שקד 41 תל אביב
אליהו ברלין 7 תל אביב
פרזון 15 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
עירית 11 תל אביב
אליעזר קפלן 19 תל אביב
אליעזר קפלן 21 תל אביב
אליעזר קפלן 25 תל אביב
אליעזר קפלן 31 תל אביב
שאול אביגור 9 תל אביב
אליהו ברלין 7 תל אביב
פנקס 76 תל אביב
בנימיני 20 תל אביב
לוינסקי 134 תל אביב
גיתית 4 תל אביב
הס 5 תל אביב
מאיר יערי 4 תל אביב
עמק ברכה 27 תל אביב
אבן סינא 54 תל אביב
הגולן 102 תל אביב
נגבה 21 תל אביב
שדרות נורדאו 80 תל אביב
שי"ר 4 תל אביב
רמה 2 תל אביב
משה פרלוק 12 תל אביב
ז'בוטינסקי 91 תל אביב
ציהתל"י 4 תל אביב
קליי 10 תל אביב
מסילת ישרים 8 תל אביב
עודד 20 תל אביב
צונץ 10 תל אביב
לכיש 3 תל אביב
שדרות נורדאו 75 תל אביב
צ'לנוב 46 תל אביב
צ'לנוב 48 תל אביב
צ'לנוב 52 תל אביב
צ'לנוב 58 תל אביב
ניסים אלוני 6 תל אביב
חסידי האומות 22 תל אביב
ילקוט הרועים 3 תל אביב
שקד 46 תל אביב
גאולה 40 תל אביב
גרציאני יצחק 4 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 10 תל אביב
גרציאני יצחק 16 תל אביב
צונץ 16 תל אביב
מיטב 1 תל אביב
החשמונאים 96 תל אביב
רמברנדט 13 תל אביב
מצובה 8 תל אביב
קמינסקה 6 תל אביב
גונן 16 תל אביב
גונן 18 תל אביב
גונן 22 תל אביב
גונן 28 תל אביב
שיינקין 4 תל אביב
המכבי 1 תל אביב
גלעינית 1 תל אביב
אבן גבירול 38 תל אביב
טשרניחובסקי 30 תל אביב
טאגור 42 תל אביב
אברבנאל 58 תל אביב
שקד 37 תל אביב
החשמונאים 100 תל אביב
הירקון 183 תל אביב
פרישמן 11 תל אביב
דרך שלמה 117 תל אביב
ד"ר אברהם אליהו הרכבי 11 תל אביב
ד"ר אברהם אליהו הרכבי 13 תל אביב
ד"ר אברהם אליהו הרכבי 17 תל אביב
ד"ר אברהם אליהו הרכבי 23 תל אביב
ארלוזורוב 17 תל אביב
ארלוזורוב 19 תל אביב
הרב קוק 17 תל אביב
לבונטין 30 תל אביב
קהילת קנדה 44 תל אביב
הרב מרק 16 תל אביב
הרב מרק 18 תל אביב
הרב מרק 22 תל אביב
הרב מרק 28 תל אביב
הרב רובינשטיין 47 תל אביב
הרב רובינשטיין 49 תל אביב
הרב רובינשטיין 53 תל אביב
הרב רובינשטיין 59 תל אביב
חזנוביץ' 10 תל אביב
חזנוביץ' 12 תל אביב
חזנוביץ' 16 תל אביב
חזנוביץ' 22 תל אביב
אייגר 14 תל אביב
פלורנטין 57 תל אביב
בארי 49 תל אביב
שמואל ירחינאי 8 תל אביב
שמואל ירחינאי 10 תל אביב
וינגייט 2 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
שדרות ששת הימים 16 תל אביב
אלעזר בן עזריה 10 תל אביב
וייצמן 30 תל אביב
משה שרת 22 תל אביב
משה וילנסקי 49 תל אביב
ניסים אלוני 4 תל אביב
החשמונאים 96 תל אביב
החשמונאים 96 תל אביב
נטעים 16 תל אביב
הרב רובינשטיין 37 תל אביב
הרב רובינשטיין 39 תל אביב
הרב רובינשטיין 43 תל אביב
הרב רובינשטיין 49 תל אביב
גרוזנברג 4 תל אביב
גרוזנברג 6 תל אביב
בן צדוק 2 תל אביב
המליץ 11 תל אביב
שדרות רוטשילד 42 תל אביב
נרדור 15 תל אביב
קהילת ונציה 18 תל אביב
קהילת ונציה 20 תל אביב
קהילת ונציה 24 תל אביב
קהילת ונציה 30 תל אביב
יוניצמן 2 תל אביב
צוקרמן 14 תל אביב
החשמונאים 100 תל אביב
שדרות ירושלים 19 תל אביב
שדרות ירושלים 21 תל אביב
שדרות ירושלים 25 תל אביב
שדרות ירושלים 31 תל אביב
שדרות לוי אשכול 35 תל אביב
שדרות לוי אשכול 37 תל אביב
שדרות לוי אשכול 41 תל אביב
שדרות לוי אשכול 47 תל אביב
הרבי מבכרך 2 תל אביב
דורון 14 תל אביב
מנחם ארבר 8 תל אביב
משה וילנסקי 31 תל אביב
קורט טוכולסקי 10 תל אביב
אמיר גלבוע 5 תל אביב
בלפור 33 תל אביב
זלמן שז"ר 55 תל אביב
ברנר 8 תל אביב
שדרות נורדאו 79 תל אביב
עברי 46 תל אביב
מעפילי אגוז 2 תל אביב
פרופ' יובל נאמן 3 תל אביב
בוקי בן יגלי 3 תל אביב
שתולים 59 תל אביב
דרך מנחם בגין 144 תל אביב
בני ברק 17 תל אביב
ליאונרדו דה וינצ'י 12 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 18 תל אביב
ליאונרדו דה וינצ'י 24 תל אביב
שדרות נורדאו 17 תל אביב
שתולים 59 תל אביב
עזרא קורין 6 תל אביב
מרדכי אנילביץ' 1 תל אביב
יהודה הימית 20 תל אביב
ניסים אלוני 6 תל אביב
שתולים 100 תל אביב
שתולים 102 תל אביב
שתולים 106 תל אביב
שתולים 112 תל אביב
פיקוס 3 תל אביב
שדרות ירושלים 221 תל אביב
אליעזר קשאני 7 תל אביב

משה קול 1 תל אביב
השלושה 1 תל אביב
ברוך קרוא 18 תל אביב
שולמית 9 תל אביב
ירמיהו 23 תל אביב
הגיבור האלמוני 54 תל אביב
פרוג 7 תל אביב
מל"ן 24 תל אביב
מתתיהו 1 תל אביב
פנקס 66 תל אביב
וינגייט 2 תל אביב
הרצל 121 תל אביב
מרחביה 17 תל אביב
פייבל 12 תל אביב
סמטת שלוש 22 תל אביב
אלכסנדר פן 6 תל אביב
פינסקר 25 תל אביב
עירית 18 תל אביב
שדרות מוצקין 4 תל אביב
שדרות מוצקין 6 תל אביב
שדרות מוצקין 10 תל אביב
שדרות מוצקין 16 תל אביב
מח"ל 2 תל אביב
מח"ל 4 תל אביב
מח"ל 8 תל אביב
מח"ל 14 תל אביב
דיזנגוף 50 תל אביב
שלמה המלך 26 תל אביב
חסידי האומות 24 תל אביב
הצנחנים 23 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
וינגייט 3 תל אביב
וינגייט 5 תל אביב
וינגייט 9 תל אביב
וינגייט 15 תל אביב
עמינדב 16 תל אביב
הרב יצחק ידידיה פרנקל 60 תל אביב
עליית הנוער 26 תל אביב
משה וילנסקי 53 תל אביב
חובבי ציון 41 תל אביב
רציף הרברט סמואל 60 תל אביב
טשרניחובסקי 47 תל אביב
הרב רובינשטיין 37 תל אביב
הרב רובינשטיין 39 תל אביב
הרב רובינשטיין 43 תל אביב
הרב רובינשטיין 49 תל אביב
פרופ' יובל נאמן 5 תל אביב
דם המכבים 10 תל אביב
זלמן שז"ר 31 תל אביב
אלוף קלמן מגן 3 תל אביב
ליאונרדו דה וינצ'י 12 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 18 תל אביב
ליאונרדו דה וינצ'י 24 תל אביב
הקליר 4 תל אביב
דרך הטייסים 48 תל אביב
אדירים 1 תל אביב
קהילת ונציה 18 תל אביב
קהילת ונציה 20 תל אביב
קהילת ונציה 24 תל אביב
קהילת ונציה 30 תל אביב
הבלונים / 3695 1 תל אביב
הבלונים / 3695 3 תל אביב
הבלונים / 3695 7 תל אביב
הבלונים / 3695 13 תל אביב
אדירים 1 תל אביב
מחרוזת 20 תל אביב
סומקן 6 תל אביב
הגדוד העברי 57 תל אביב
הקלעים 7 תל אביב
ברגסון 7 תל אביב
קמינסקה 4 תל אביב
הירקון 19 תל אביב
שדרות נורדאו 9 תל אביב
הרב רובינשטיין 45 תל אביב
הרב רובינשטיין 47 תל אביב
הרב רובינשטיין 51 תל אביב
הרב רובינשטיין 57 תל אביב
כיכר היל 3 תל אביב
ליאונרדו דה וינצ'י 12 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 18 תל אביב
ליאונרדו דה וינצ'י 24 תל אביב
בזל 33 תל אביב
הרב ניסים 9 תל אביב
הרב ניסים 11 תל אביב
דרך הטייסים 53 תל אביב
דרך הטייסים 55 תל אביב
דרך הטייסים 59 תל אביב
דרך הטייסים 65 תל אביב
יונה הנביא 30 תל אביב
ארלוזורוב 156 תל אביב
צונץ 1 תל אביב
שדרות נורדאו 88 תל אביב
הגיבור האלמוני 50 תל אביב
אלנבי 13 תל אביב
דרך משה דיין 33 תל אביב
מגידו 4 תל אביב
יאנוש קורצ'אק 17 תל אביב
אחימעץ 37 תל אביב
אחימעץ 39 תל אביב
הפרטיזן היהודי 26 תל אביב
בן יהודה 53 תל אביב
שלומציון המלכה 40 תל אביב
דיזנגוף 135 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
גרציאני יצחק 4 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 10 תל אביב
גרציאני יצחק 16 תל אביב
חכמי אתונה 57 תל אביב
דבורה הנביאה 4 תל אביב
ישראל גלילי 6 תל אביב
ברדיצ'בסקי 17 תל אביב
גרציאני יצחק 4 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 10 תל אביב
גרציאני יצחק 16 תל אביב
נחום סוקולוב 5 תל אביב
נחום סוקולוב 7 תל אביב
נחום סוקולוב 11 תל אביב
נחום סוקולוב 17 תל אביב
וכטנגוב 11 תל אביב
בן יהודה 51 תל אביב
שדרות לוי אשכול 47 תל אביב
שדרות לוי אשכול 49 תל אביב
שדרות לוי אשכול 53 תל אביב
שדרות לוי אשכול 59 תל אביב
אלוף קלמן מגן 7 תל אביב
י.ל. פרץ 35 תל אביב
י.ל. פרץ 37 תל אביב
י.ל. פרץ 41 תל אביב
י.ל. פרץ 47 תל אביב
יהודה הנשיא 39 תל אביב
ישראל מסלנט 7 תל אביב
דקל 3 תל אביב
וולפסון 54 תל אביב
פנקס 76 תל אביב
יסוד המעלה 6 תל אביב
אשרמן 10 תל אביב
אדירים 1 תל אביב
עמינדב 20 תל אביב
החשמונאים 100 תל אביב
קורט טוכולסקי 8 תל אביב
רש"י 15 תל אביב
אפטר 6 תל אביב
שדרות לוי אשכול 4 תל אביב
שדרות לוי אשכול 6 תל אביב
שדרות לוי אשכול 10 תל אביב
שדרות לוי אשכול 16 תל אביב
הגדוד העברי 59 תל אביב
החשמונאים 96 תל אביב
קהילת לודז' 44 תל אביב
קהילת לודז' 46 תל אביב
קהילת לודז' 50 תל אביב
קהילת לודז' 56 תל אביב
לבונטין 19 תל אביב
רמז 36 תל אביב
דרך הטייסים 104 תל אביב
דרך הטייסים 106 תל אביב
דרך הטייסים 110 תל אביב
סומקן 26 תל אביב
רבינא 11 תל אביב
החשמונאים 96 תל אביב
שדרות נורדאו 88 תל אביב
לכיש 7 תל אביב
פייבל 4 תל אביב
נחמיה 13 תל אביב
בן שפרוט 2 תל אביב
שילה 8 תל אביב
מרסל ינקו 18 תל אביב
קהילת קנדה 20 תל אביב
דרך מנחם בגין 144 תל אביב
האחים אל כוויתי 5 תל אביב
יהודה הנשיא 39 תל אביב
מזא"ה 66 תל אביב
מזא"ה 68 תל אביב
מזא"ה 72 תל אביב
מזא"ה 78 תל אביב
בית אל 47 תל אביב
דיזנגוף 342 תל אביב
לוינסקי 2 תל אביב
רמברנדט 36 תל אביב
חנה רובינא 7 תל אביב
ג'ורג' אליוט 5 תל אביב
מעפילי אגוז 3 תל אביב
וינגייט 1 תל אביב
וינגייט 3 תל אביב
וינגייט 7 תל אביב
וינגייט 13 תל אביב
קהילת ניו יורק 44 תל אביב
יצחק אלחנן 15 תל אביב
הרב יעקב ריפמן 9 תל אביב
הרב יעקב ריפמן 11 תל אביב
הרב יעקב ריפמן 15 תל אביב
הרב יעקב ריפמן 21 תל אביב
יוסף קארו 25 תל אביב
מיטב 5 תל אביב
מיטב 7 תל אביב
סומקן 15 תל אביב
נרדור 15 תל אביב
דרך משה דיין 53 תל אביב
הקשת 2 תל אביב
ניסים אלוני 2 תל אביב
פרנץ קפקא 4 תל אביב
אלכסנדר סשה ארגוב 5 תל אביב
אלכסנדר סשה ארגוב 7 תל אביב
אלכסנדר סשה ארגוב 11 תל אביב
אלכסנדר סשה ארגוב 17 תל אביב
ניסים אלוני 10 תל אביב
פרופ' יובל נאמן 11 תל אביב
אייר 12 תל אביב
אייר 14 תל אביב
אייר 18 תל אביב
אייר 24 תל אביב
ניסים אלוני 16 תל אביב
צוקרמן 23 תל אביב
נחום סוקולוב 69 תל אביב
נחום סוקולוב 71 תל אביב
נחום סוקולוב 75 תל אביב
נחום סוקולוב 81 תל אביב
אלנבי 1 תל אביב
הירקון 80 תל אביב
אוריאל אקוסטה 16 תל אביב
בארט 5 תל אביב
ילקוט הרועים 1 תל אביב
ארלוזורוב 17 תל אביב
ארלוזורוב 19 תל אביב
ענתות 35 תל אביב
הירקון 204 תל אביב
אנטוקולסקי 8 תל אביב
פאת השולחן 5 תל אביב
עליית הנוער 14 תל אביב
בן סרוק 24 תל אביב
הרב ניסים 9 תל אביב
הרב ניסים 11 תל אביב
לסר אורי 4 תל אביב
אוסישקין 96 תל אביב
שדרות שאול המלך 1 תל אביב
שלום עליכם 42 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
הגר"א 10 תל אביב
שדרות מוצקין 20 תל אביב
שדרות מוצקין 22 תל אביב
שדרות מוצקין 26 תל אביב
שדרות מוצקין 32 תל אביב
2380 2 תל אביב
2380 4 תל אביב
2380 8 תל אביב
2380 14 תל אביב
רוממה 40 תל אביב
רוממה 42 תל אביב
רוממה 46 תל אביב
רוממה 52 תל אביב
דרך מנחם בגין 144 תל אביב
אצ"ל 67 תל אביב
ליאונרדו דה וינצ'י 12 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 18 תל אביב
ליאונרדו דה וינצ'י 24 תל אביב
שתולים 55 תל אביב
קהילת פאדובה 19 תל אביב
ביל"ו 10 תל אביב
וינגייט 1 תל אביב
וינגייט 3 תל אביב
וינגייט 7 תל אביב
וינגייט 13 תל אביב
דרך ההגנה 132 תל אביב
ליאונרדו דה וינצ'י 3 תל אביב
מיטב 5 תל אביב
מיטב 7 תל אביב
בן יהודה 158 תל אביב
דרך מנחם בגין 31 תל אביב
דרך מנחם בגין 33 תל אביב
דרך מנחם בגין 37 תל אביב
קורדוברו 14 תל אביב
התקומה 24 תל אביב
סומקן 32 תל אביב
ד"ר אלי תבין 3 תל אביב
תרצה 23 תל אביב
בית פלט 22 תל אביב
בית פלט 24 תל אביב
גרציאני יצחק 1 תל אביב
גרציאני יצחק 3 תל אביב
גרציאני יצחק 7 תל אביב
גרציאני יצחק 13 תל אביב
שדרות ח"ן 59 תל אביב
פנקס 19 תל אביב
ז'אן ז'ורס 8 תל אביב
לה גווארדיה 64 תל אביב
לוינסקי 66 תל אביב
לוינסקי 68 תל אביב
לוינסקי 72 תל אביב
לוינסקי 78 תל אביב
משה וילנסקי 49 תל אביב
עמישב 22 תל אביב
משה בריל 5 תל אביב
ריינס 45 תל אביב
יהודה עמיחי 14 תל אביב
האסיף 18 תל אביב
אליעזר קפלן 19 תל אביב
אליעזר קפלן 21 תל אביב
אליעזר קפלן 25 תל אביב
אליעזר קפלן 31 תל אביב
פוריה 12 תל אביב
שתולים 100 תל אביב
שתולים 102 תל אביב
שתולים 106 תל אביב
שתולים 112 תל אביב
דרך חיים ברלב 119 תל אביב
ליאונרדו דה וינצ'י 12 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 18 תל אביב
ליאונרדו דה וינצ'י 24 תל אביב
גאולה 40 תל אביב
הקשת 23 תל אביב
דרך חיל השריון 92 תל אביב
זלמן שניאור 4 תל אביב
דרך הטייסים 86 תל אביב
ד"ר אלי תבין 1 תל אביב
הכינור 1 תל אביב
דבורה הנביאה 13 תל אביב
אהבת ציון 23 תל אביב
ניסים אלוני 2 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 16 תל אביב
ליאונרדו דה וינצ'י 20 תל אביב
ליאונרדו דה וינצ'י 26 תל אביב
לוחמי גליפולי 24 תל אביב
שלמה המלך 33 תל אביב
לח"י 36 תל אביב
ישראליס 19 תל אביב
זלמן שניאור 15 תל אביב
עמינדב 16 תל אביב
שתולים 59 תל אביב
שדרות ההשכלה 17 תל אביב
בושם 66 תל אביב
אוסישקין 58 תל אביב
ניסים אלוני 2 תל אביב
התקווה 19 תל אביב
וייצמן 99 תל אביב
אוארבך 2 תל אביב
הרב קוסובסקי 30 תל אביב
מעפילי אגוז 82 תל אביב
בני אפרים 210 תל אביב
חובבי ציון 14 תל אביב
ארתור רובינשטיין 7 תל אביב
שמעון בן שטח 5 תל אביב
פנקס 19 תל אביב
הרצל רוזנבלום 12 תל אביב
חכמי אתונה 56 תל אביב
הגולן 102 תל אביב
החשמונאים 96 תל אביב
גר צדק 7 תל אביב
שלום עליכם 18 תל אביב
שדרות לוי אשכול 2 תל אביב
שדרות לוי אשכול 4 תל אביב
שדרות לוי אשכול 8 תל אביב
שדרות לוי אשכול 14 תל אביב
הירקון 80 תל אביב
אלנבי 1 תל אביב
פרופ' יובל נאמן 3 תל אביב
עזאי 100 תל אביב
עזאי 102 תל אביב
עזאי 106 תל אביב
עזאי 112 תל אביב
הרב יוסף צוברי 22 תל אביב
דרך חיים ברלב 175 תל אביב
החשמונאים 94 תל אביב
לסקר 16 תל אביב
דיזנגוף 107 תל אביב
טשרניחובסקי 8 תל אביב

בן יהודה 31 תל אביב
ניסים אלוני 17 תל אביב
לייוויק 3 תל אביב
זלמן שז"ר 33 תל אביב
מעפילי אגוז 9 תל אביב
שדרות רוטשילד 17 תל אביב
הקישון 72 תל אביב
שדרות יהודית 1 תל אביב
מרים החשמונאית 21 תל אביב
מח"ל 83 תל אביב
חפר 2 תל אביב
בן שפרוט 5 תל אביב
שלומציון המלכה 40 תל אביב
שיק 20 תל אביב
שילה 8 תל אביב
דבורה הנביאה 71 תל אביב
הדסה 6 תל אביב
וייצמן 30 תל אביב
אוסישקין 90 תל אביב
שמואל הנגיד 6 תל אביב
נחמני 55 תל אביב
נחמני 57 תל אביב
נחמני 61 תל אביב
נחמני 67 תל אביב
מוסינזון 21 תל אביב
צוקרמן 6 תל אביב
לינקולן 5 תל אביב
השוק 43 תל אביב
הרב יצחק ידידיה פרנקל 22 תל אביב
נחום סוקולוב 30 תל אביב
נחום סוקולוב 32 תל אביב
נחום סוקולוב 36 תל אביב
נחום סוקולוב 42 תל אביב
גוש עציון 13 תל אביב
ארלוזורוב 17 תל אביב
ארלוזורוב 19 תל אביב
מנחם ארבר 33 תל אביב
מנחם ארבר 13 תל אביב
מנחם ארבר 15 תל אביב
דיזנגוף 50 תל אביב
דרך הטייסים 50 תל אביב
דרך מנחם בגין 144 תל אביב
ארלוזורוב 17 תל אביב
ארלוזורוב 19 תל אביב
החשמונאים 100 תל אביב
שלום עליכם 17 תל אביב
זרובבל 19 תל אביב
אוהלי יעקב 11 תל אביב
שדרות הר ציון 37 תל אביב
שדרות ששת הימים 16 תל אביב
כורזים 6 תל אביב
אסתר המלכה 8 תל אביב
דוד ילין 7 תל אביב
יוניצמן 21 תל אביב
יוניצמן 23 תל אביב
יוניצמן 27 תל אביב
יוניצמן 33 תל אביב
שלמון 24 תל אביב
מבצע קדש 4 תל אביב
זלמן שז"ר 73 תל אביב
אילת 61 תל אביב
ורדיאל 21 תל אביב
גרוזנברג 37 תל אביב
ש"ץ 15 תל אביב
אלכסנדר ינאי 23 תל אביב
וורמייזה 15 תל אביב
אביגדור המאירי 17 תל אביב
חיננית 6 תל אביב
ניסים אלוני 4 תל אביב
ליאונרדו דה וינצ'י 13 תל אביב
ציהתל"י 49 תל אביב
הירקון 110 תל אביב
כהנשטם 2 תל אביב
ברוריה 24 תל אביב
מיכלאנג'לו 8 תל אביב
מיכלאנג'לו 10 תל אביב
מיכלאנג'לו 14 תל אביב
מיכלאנג'לו 20 תל אביב
פין 1 תל אביב
הרב ניסים 9 תל אביב
הרב ניסים 11 תל אביב
גרציאני יצחק 4 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 10 תל אביב
גרציאני יצחק 16 תל אביב
דרך משה דיין 24 תל אביב
משה שרת 88 תל אביב
משה שרת 22 תל אביב
ד"ר אברהם אליהו הרכבי 9 תל אביב
ד"ר אברהם אליהו הרכבי 11 תל אביב
ד"ר אברהם אליהו הרכבי 15 תל אביב
ד"ר אברהם אליהו הרכבי 21 תל אביב
אפ"ק 2 תל אביב
פינסקר 36 תל אביב
האחים אל כוויתי 3 תל אביב
משה שרת 22 תל אביב
דיזנגוף 235 תל אביב
זלמן שז"ר 51 תל אביב
הרכבת 16 תל אביב
חובבי ציון 17 תל אביב
מקווה ישראל 4 תל אביב
וינגייט 3 תל אביב
וינגייט 5 תל אביב
וינגייט 9 תל אביב
וינגייט 15 תל אביב
בעל העקידה 27 תל אביב
ניסים אלוני 17 תל אביב
דרך מנחם בגין 144 תל אביב
שילה 5 תל אביב
מרסל ינקו 14 תל אביב
הגיבור האלמוני 33 תל אביב
שדרות ירושלים 221 תל אביב
רמה 2 תל אביב
פרץ חיות 12 תל אביב
רש"י 15 תל אביב
ראול ולנברג 2 תל אביב
ישה חפץ 5 תל אביב
ליאונרדו דה וינצ'י 3 תל אביב
י.ל. פרץ 35 תל אביב
י.ל. פרץ 37 תל אביב
י.ל. פרץ 41 תל אביב
י.ל. פרץ 47 תל אביב
אבן גבירול 44 תל אביב
קדושי השואה 12 תל אביב
שדרות לוי אשכול 100 תל אביב
שדרות לוי אשכול 102 תל אביב
שדרות לוי אשכול 106 תל אביב
שדרות לוי אשכול 112 תל אביב
שדרות הר ציון 43 תל אביב
נגבה 21 תל אביב
הירקון 80 תל אביב
עמינדב 20 תל אביב
כביר 1 תל אביב
אליפלט 26 תל אביב
אליפלט 28 תל אביב
אליפלט 32 תל אביב
נהלל 12 תל אביב
שבזי 6 תל אביב
אלנבי 32 תל אביב
החשמונאים 96 תל אביב
שלוש 6 תל אביב
עמישב 44 תל אביב
קמינסקה 26 תל אביב
בושם 74 תל אביב
שדרות רוטשילד 36 תל אביב
החשמונאים 100 תל אביב
הרב קוסובסקי 30 תל אביב
ויינשל 19 תל אביב
קורט טוכולסקי 6 תל אביב
פינס 39 תל אביב
פינס 41 תל אביב
פינס 45 תל אביב
פינס 51 תל אביב
דיזנגוף 135 תל אביב
שלום עליכם 17 תל אביב
עמק ברכה 13 תל אביב
מלצ'ט 32 תל אביב
מעפילי אגוז 104 תל אביב
הגיבור האלמוני 46 תל אביב
הרצל רוזנבלום 10 תל אביב
קדש ברנע 3 תל אביב
עזרא הסופר 18 תל אביב
פלורנטין 45 תל אביב
רמברנדט 34 תל אביב
הירקון 49 תל אביב
עמק ברכה 19 תל אביב
מרים החשמונאית 14 תל אביב
גאולה 29 תל אביב
משה שרת 40 תל אביב
לוינסקי 66 תל אביב
לוינסקי 68 תל אביב
לוינסקי 72 תל אביב
לוינסקי 78 תל אביב
בלפור 8 תל אביב
ליאונרדו דה וינצ'י 1 תל אביב
שבתאי 29 תל אביב
פלוגות 14 תל אביב
התקווה 99 תל אביב
שדרות לוי אשכול 100 תל אביב
שדרות לוי אשכול 102 תל אביב
שדרות לוי אשכול 106 תל אביב
שדרות לוי אשכול 112 תל אביב
שלומציון המלכה 40 תל אביב
בזל 21 תל אביב
שטריקר 62 תל אביב
דרך קיבוץ גלויות 91 תל אביב
קרליבך 4 תל אביב
החשמונאים 98 תל אביב
פרישמן 25 תל אביב
ה' באייר 72 תל אביב
אלכסנדר סשה ארגוב 31 תל אביב
אלכסנדר סשה ארגוב 33 תל אביב
אלכסנדר סשה ארגוב 37 תל אביב
אלכסנדר סשה ארגוב 43 תל אביב
החשמונאים 80 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
מח"ל 70 תל אביב
דרך ההגנה 29 תל אביב
שדרות ששת הימים 30 תל אביב
תוצרת הארץ 5 תל אביב
יהודה הימית 35 תל אביב
שמואל רומנילי 1 תל אביב
צונזר 4 תל אביב
שלמה המלך 99 תל אביב
אלנבי 1 תל אביב
שדרות ההשכלה 17 תל אביב
אייגר 14 תל אביב
יוניצמן 21 תל אביב
יוניצמן 23 תל אביב
יוניצמן 27 תל אביב
יוניצמן 33 תל אביב
סוטין 29 תל אביב
חסידי האומות 22 תל אביב
ליאונרדו דה וינצ'י 12 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 18 תל אביב
ליאונרדו דה וינצ'י 24 תל אביב
דיזנגוף 269 תל אביב
אלכסנדר סשה ארגוב 13 תל אביב
אלכסנדר סשה ארגוב 15 תל אביב
אלכסנדר סשה ארגוב 19 תל אביב
אלכסנדר סשה ארגוב 25 תל אביב
בית אל 20 תל אביב
בלפור 8 תל אביב
ישה חפץ 1 תל אביב
מח"ל 70 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 8 תל אביב
גרציאני יצחק 12 תל אביב
גרציאני יצחק 18 תל אביב
הירקון 47 תל אביב
חידושי הרי"ם 3 תל אביב
נחלת יצחק 14 תל אביב
שדרות ירושלים 63 תל אביב
מעפילי אגוז 15 תל אביב
שדרות ירושלים 137 תל אביב
רחבת הסיירים 3 תל אביב
הרטוב 9 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 8 תל אביב
גרציאני יצחק 12 תל אביב
גרציאני יצחק 18 תל אביב
בושם 74 תל אביב
קמינסקה 24 תל אביב
משגב עם 4 תל אביב
בית אל 12 תל אביב
דב ממזריץ' 12 תל אביב
צונץ 3 תל אביב
החשמונאים 61 תל אביב
דרך מנחם בגין 150 תל אביב
דב הוז 12 תל אביב
מעפילי אגוז 24 תל אביב
מעפילי אגוז 26 תל אביב
מעפילי אגוז 30 תל אביב
מעפילי אגוז 36 תל אביב
בעל הטורים 4 תל אביב
הרב אלנקווה 76 תל אביב
דרך מנחם בגין 144 תל אביב
ארלוזורוב 17 תל אביב
ארלוזורוב 19 תל אביב
רציף הרברט סמואל 10 תל אביב
רציף הרברט סמואל 12 תל אביב
רציף הרברט סמואל 16 תל אביב
רציף הרברט סמואל 22 תל אביב
2380 1 תל אביב
2380 3 תל אביב
2380 7 תל אביב
2380 13 תל אביב
דרך משה דיין 44 תל אביב
משגב עם 16 תל אביב
וינגייט 2 תל אביב
זלטופולסקי 21 תל אביב
וינגייט 3 תל אביב
וינגייט 5 תל אביב
וינגייט 9 תל אביב
וינגייט 15 תל אביב
הגיבור האלמוני 26 תל אביב
נחלת יצחק 37 תל אביב
מיכאל נאמן 18 תל אביב
וילסון 13 תל אביב
דבורה הנביאה 4 תל אביב
ליאונרדו דה וינצ'י 12 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 18 תל אביב
ליאונרדו דה וינצ'י 24 תל אביב
קמינסקה 26 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 16 תל אביב
ליאונרדו דה וינצ'י 20 תל אביב
ליאונרדו דה וינצ'י 26 תל אביב
שילה 8 תל אביב
הרב אלנקווה 11 תל אביב
נגבה 32 תל אביב
ניסים אלוני 21 תל אביב
אחווה 8 תל אביב
מח"ל 2 תל אביב
מח"ל 4 תל אביב
מח"ל 8 תל אביב
מח"ל 14 תל אביב
השלושה 3 תל אביב
צ'לנוב 32 תל אביב
צ'לנוב 34 תל אביב
צ'לנוב 38 תל אביב
צ'לנוב 44 תל אביב
רבנו ירוחם 5 תל אביב
ורשבסקי 16 תל אביב
ברנר 8 תל אביב
ה' באייר 72 תל אביב
אדירים 1 תל אביב
אוסוולדו ארניה 10 תל אביב
אוסוולדו ארניה 12 תל אביב
אוסוולדו ארניה 16 תל אביב
אוסוולדו ארניה 22 תל אביב
בושם 8 תל אביב
קורדוברו 14 תל אביב
עירית 18 תל אביב
בר גיורא 21 תל אביב
החבצלת 11 תל אביב
ביצרון 30 תל אביב
הקונגרס 16 תל אביב
הקונגרס 18 תל אביב
הקונגרס 22 תל אביב
הקונגרס 28 תל אביב
קמינסקה 24 תל אביב
מיטב 5 תל אביב
מיטב 7 תל אביב
מוסינזון 21 תל אביב
רבי חנינא 24 תל אביב
דיזנגוף 291 תל אביב
יהודה בורלא 11 תל אביב
דיזנגוף 241 תל אביב
עבד אל ראוף אלביטאר 6 תל אביב
עבד אל ראוף אלביטאר 8 תל אביב
עבד אל ראוף אלביטאר 12 תל אביב
עבד אל ראוף אלביטאר 18 תל אביב
דה האז 10 תל אביב
עמינדב 18 תל אביב
ניסים אלוני 1 תל אביב
פעמונית 20 תל אביב
חסידי האומות 24 תל אביב
הגדוד העברי 47 תל אביב
קרליבך 4 תל אביב
מחרוזת 14 תל אביב
שמריהו לוין 13 תל אביב
יהודה המכבי 3 תל אביב
דורון 14 תל אביב
בבלי 1 תל אביב
משה בריל 9 תל אביב
פלורנטין 46 תל אביב
טשרניחובסקי 24 תל אביב
השילוח 14 תל אביב
השל"ה 1 תל אביב
ניסים אלוני 1 תל אביב
מחרוזת 10 תל אביב
חובבי ציון 14 תל אביב
ניסים אלוני 1 תל אביב
שדרות ישראל גורי 4 תל אביב
חלמית 2 תל אביב
לוינסקי 9 תל אביב
הזמיר 9 תל אביב
שתולים 57 תל אביב
החשמונאים 100 תל אביב
אריאל 4 תל אביב
יהודה הימית 6 תל אביב
לואי מרשל 10 תל אביב
יהודה בורלא 24 תל אביב
מזל אריה 10 תל אביב
מזל אריה 12 תל אביב
פאת השולחן 5 תל אביב
חידושי הרי"ם 5 תל אביב
נגבה 15 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 8 תל אביב
גרציאני יצחק 12 תל אביב
גרציאני יצחק 18 תל אביב
עמינדב 18 תל אביב
שטנד 9 תל אביב
בית אשל 31 תל אביב
דרך משה דיין 34 תל אביב
דרך משה דיין 36 תל אביב
דרך משה דיין 40 תל אביב
שלמה שילר 11 תל אביב
שלמה שילר 13 תל אביב
שלמה שילר 17 תל אביב
שלמה שילר 23 תל אביב
וינגייט 1 תל אביב

וינגייט 3 תל אביב
וינגייט 7 תל אביב
וינגייט 13 תל אביב
עזה 2 תל אביב
צרעה 14 תל אביב
מטלון 80 תל אביב
מטלון 82 תל אביב
נגבה 15 תל אביב
מרכז בעלי מלאכה 30 תל אביב
דרך חיים ברלב 121 תל אביב
ענתות 37 תל אביב
שדרות ירושלים 113 תל אביב
הרב אלנקווה 46 תל אביב
הרב אלנקווה 48 תל אביב
הרב אלנקווה 52 תל אביב
כוכבי יצחק 5 תל אביב
קהילת ורשה 79 תל אביב
הבשן 14 תל אביב
גאולה 40 תל אביב
ענתות 35 תל אביב
נח 9 תל אביב
גיתית 8 תל אביב
קורט טוכולסקי 6 תל אביב
יחזקאל שטרייכמן 12 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 8 תל אביב
גרציאני יצחק 12 תל אביב
גרציאני יצחק 18 תל אביב
ד"ר אברהם אליהו הרכבי 9 תל אביב
ד"ר אברהם אליהו הרכבי 11 תל אביב
ד"ר אברהם אליהו הרכבי 15 תל אביב
ד"ר אברהם אליהו הרכבי 21 תל אביב
השוק 45 תל אביב
מעפילי אגוז 58 תל אביב
גרינבוים 25 תל אביב
מוריץ דניאל 36 תל אביב
ליאונרדו דה וינצ'י 13 תל אביב
מעפילי אגוז 104 תל אביב
שדרות ירושלים 46 תל אביב
טשרניחובסקי 5 תל אביב
פתחיה מרגנשבורג 20 תל אביב
פנקס 19 תל אביב
אילת 4 תל אביב
שדרות נורדאו 80 תל אביב
מוריץ דניאל 48 תל אביב
ליבנה 9 תל אביב
יוחנן הורקנוס 27 תל אביב
דרך מנחם בגין 150 תל אביב
חנה אורלוף 3 תל אביב
שדרות רוטשילד 36 תל אביב
חזנוביץ' 10 תל אביב
חזנוביץ' 12 תל אביב
חזנוביץ' 16 תל אביב
חזנוביץ' 22 תל אביב
סוטין 15 תל אביב
מח"ל 64 תל אביב
דרך השלום 101 תל אביב
דרך מנחם בגין 144 תל אביב
קהילת לודז' 44 תל אביב
קהילת לודז' 46 תל אביב
קהילת לודז' 50 תל אביב
קהילת לודז' 56 תל אביב
רמה 2 תל אביב
החשמונאים 96 תל אביב
שדרות נורדאו 7 תל אביב
דיזנגוף 137 תל אביב
אלברט קיוסו 3 תל אביב
ברוך קרוא 7 תל אביב
וינגייט 5 תל אביב
וינגייט 7 תל אביב
וינגייט 11 תל אביב
וינגייט 17 תל אביב
אוהלי יעקב 5 תל אביב
דימונה 5 תל אביב
גאולה 41 תל אביב
הרב צירלסון 13 תל אביב
פנקס 54 תל אביב
גרציאני יצחק 4 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 10 תל אביב
גרציאני יצחק 16 תל אביב
תל גיבורים 34 תל אביב
הקונגרס 9 תל אביב
שדרות ההשכלה 17 תל אביב
שילה 8 תל אביב
בלקינד 3 תל אביב
שילה 8 תל אביב
פרחי אביב 10 תל אביב
בני אפרים 205 תל אביב
האתרוג 12 תל אביב
בושם 46 תל אביב
סוטין 15 תל אביב
הנביאים 15 תל אביב
משה שרת 40 תל אביב
מטלון 78 תל אביב
מטלון 80 תל אביב
מטלון 84 תל אביב
איתיאל 15 תל אביב
נחלת בנימין 133 תל אביב
צונץ 1 תל אביב
מטלון 49 תל אביב
מטלון 51 תל אביב
מטלון 55 תל אביב
מטלון 61 תל אביב
יהודה בורלא 42 תל אביב
הירקון 70 תל אביב
ציהתל"י 57 תל אביב
משה שרת 40 תל אביב
אבן גבירול 135 תל אביב
החלוצים 34 תל אביב
בית אל 41 תל אביב
פטרסון 1 תל אביב
החשמונאים 100 תל אביב
עמישב 22 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
ריינס 48 תל אביב
נרדור 5 תל אביב
מעפילי אגוז 104 תל אביב
אסירי ציון 19 תל אביב
ערבי נחל 20 תל אביב
אייבשיץ 10 תל אביב
עין הקורא 13 תל אביב
מיכלאנג'לו 4 תל אביב
מיכלאנג'לו 6 תל אביב
מיכלאנג'לו 10 תל אביב
מיכלאנג'לו 16 תל אביב
הרטוב 21 תל אביב
הרב יצחק ידידיה פרנקל 23 תל אביב
בית אל 4 תל אביב
דרך מנחם בגין 144 תל אביב
וינגייט 4 תל אביב
יחיאל דב דרזנר 12 תל אביב
עמישב 22 תל אביב
ניסים אלוני 4 תל אביב
מטמון כהן 7 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 16 תל אביב
ליאונרדו דה וינצ'י 20 תל אביב
ליאונרדו דה וינצ'י 26 תל אביב
מחרוזת 37 תל אביב
שדרות רוקח 51 תל אביב
שדרות רוקח 53 תל אביב
שדרות רוקח 57 תל אביב
שדרות רוקח 63 תל אביב
מאפו 22 תל אביב
בית אל 39 תל אביב
קורדוברו 13 תל אביב
שדרות לוי אשכול 90 תל אביב
שדרות לוי אשכול 92 תל אביב
שדרות לוי אשכול 96 תל אביב
שדרות לוי אשכול 102 תל אביב
הרצל רוזנבלום 12 תל אביב
שמעון התרסי 4 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 16 תל אביב
ליאונרדו דה וינצ'י 20 תל אביב
ליאונרדו דה וינצ'י 26 תל אביב
וינגייט 2 תל אביב
משה קול 8 תל אביב
קורולנקו 4 תל אביב
גרציאני יצחק 4 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 10 תל אביב
גרציאני יצחק 16 תל אביב
משה וילנסקי 47 תל אביב
פלורנטין 45 תל אביב
דיזנגוף 255 תל אביב
עמינדב 18 תל אביב
ה' באייר 38 תל אביב
מעפילי אגוז 85 תל אביב
הנרייטה סולד 2 תל אביב
סירקין 10 תל אביב
ניסים אלוני 16 תל אביב
משה בריל 14 תל אביב
מורדי הגטאות 21 תל אביב
אשרמן 7 תל אביב
ניסים אלוני 21 תל אביב
דיזנגוף 172 תל אביב
מוהליבר 43 תל אביב
איסר יהודה אונטרמן 8 תל אביב
פלוגות 16 תל אביב
וינגייט 2 תל אביב
שתולים 61 תל אביב
אייגר 20 תל אביב
משה קול 1 תל אביב
ישעיהו 22 תל אביב
מוסינזון 21 תל אביב
מולדת 1 תל אביב
מולדת 3 תל אביב
מולדת 7 תל אביב
מולדת 13 תל אביב
אליהו בית צורי 10 תל אביב
סמטת נורדאו 7 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
איתמר בן אב"י 7 תל אביב
ביירון 12 תל אביב
עמישב 22 תל אביב
טרומפלדור 37 תל אביב
מזא"ה 74 תל אביב
מזא"ה 76 תל אביב
מזא"ה 80 תל אביב
מזא"ה 86 תל אביב
מח"ל 72 תל אביב
דרך הטייסים 46 תל אביב
ציהתל"י 14 תל אביב
ציהתל"י 16 תל אביב
ציהתל"י 20 תל אביב
ציהתל"י 26 תל אביב
אפלטון 1 תל אביב
הירקון 80 תל אביב
זאב 11 תל אביב
אלכסנדר פן 12 תל אביב
לוינסקי 9 תל אביב
שמריהו לוין 3 תל אביב
יוסף פעמוני 10 תל אביב
משה וילנסקי 49 תל אביב
אבן גבירול 160 תל אביב
יעקב מוזר 3 תל אביב
יעקב מוזר 5 תל אביב
יעקב מוזר 9 תל אביב
יעקב מוזר 15 תל אביב
3628 8 תל אביב
3628 10 תל אביב
3628 14 תל אביב
3628 20 תל אביב
מח"ל 14 תל אביב
מח"ל 16 תל אביב
מח"ל 20 תל אביב
הזוהר 2 תל אביב
הזוהר 4 תל אביב
השל"ה 13 תל אביב
אוסישקין 38 תל אביב
דרך השלום 113 תל אביב
שיינקין 49 תל אביב
בילויה מעוז 8 תל אביב
שתולים 100 תל אביב
שתולים 102 תל אביב
שתולים 106 תל אביב
שתולים 112 תל אביב
כנרת 5 תל אביב
בושם 8 תל אביב
שלומציון המלכה 17 תל אביב
ברזיל 16 תל אביב
אלכסנדר ינאי 6 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
שדרות ששת הימים 5 תל אביב
דולצ'ין 10 תל אביב
צידון 4 תל אביב
שבטי ישראל 30 תל אביב
דרך שלמה 54 תל אביב
חסידי האומות 6 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
ניסים אלוני 6 תל אביב
החשמונאים 100 תל אביב
לבונטין 30 תל אביב
שדרות ירושלים 13 תל אביב
משה וילנסקי 69 תל אביב
משה וילנסקי 71 תל אביב
משה וילנסקי 75 תל אביב
משה וילנסקי 81 תל אביב
שי"ר 4 תל אביב
שתולים 63 תל אביב
העבודה 4 תל אביב
יהודה בורלא 12 תל אביב
קרליבך 4 תל אביב
עודד 18 תל אביב
אסירי ציון 17 תל אביב
דרך ההגנה 146 תל אביב
כוכבי יצחק 13 תל אביב
בן יהודה 13 תל אביב
דרך משה דיין 34 תל אביב
דרך משה דיין 36 תל אביב
דרך משה דיין 40 תל אביב
החלוצים 48 תל אביב
הנוטר 29 תל אביב
סוטין 29 תל אביב
מח"ל 60 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
משמר הגבול 13 תל אביב
נחמני 15 תל אביב
דרך הטייסים 76 תל אביב
דרך משה דיין 18 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
הרב ניסים 9 תל אביב
הרב ניסים 11 תל אביב
יעקב סלע 2 תל אביב
אהבת ציון 27 תל אביב
מאיר יערי 12 תל אביב
מורדי הגטאות 27 תל אביב
ויטל 23 תל אביב
יהודה הלוי 125 תל אביב
בן שפרוט 2 תל אביב
יפתח 16 תל אביב
צייטלין 9 תל אביב
הרב ניסים 9 תל אביב
הרב ניסים 11 תל אביב
הרב אלנקווה 40 תל אביב
הרב אלנקווה 42 תל אביב
הרב אלנקווה 46 תל אביב
הרב אלנקווה 52 תל אביב
חסידי האומות 24 תל אביב
קהילת ברזיל 2 תל אביב
צהלון הרופא 5 תל אביב
בבלי 27 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
מטלון 78 תל אביב
מטלון 80 תל אביב
מטלון 84 תל אביב
חובבי ציון 17 תל אביב
ארלוזורוב 17 תל אביב
ארלוזורוב 19 תל אביב
דרור 15 תל אביב
אורי צבי גרינברג 4 תל אביב
דיזנגוף 298 תל אביב
הגולן 100 תל אביב
אבן גבירול 160 תל אביב
חיננית 7 תל אביב
החשמונאים 100 תל אביב
וייסבורג 24 תל אביב
פישמן מיימון 7 תל אביב
הרצל 108 תל אביב
הקונגרס 13 תל אביב
הרצל 121 תל אביב
בן שפרוט 2 תל אביב
הקונגרס 13 תל אביב
רמב"ם 4 תל אביב
יהודה הימית 40 תל אביב
אליפלט 26 תל אביב
אליפלט 28 תל אביב
אליפלט 32 תל אביב
הקישון 75 תל אביב
הפטמן 1 תל אביב
צלילי חנינא 42 תל אביב
פרופ' יובל נאמן 5 תל אביב
דיק 6 תל אביב
החשמונאים 96 תל אביב
אוסישקין 4 תל אביב
עירית 18 תל אביב
בזל 35 תל אביב
השופר 4 תל אביב
החשמונאים 100 תל אביב
שדרות לוי אשכול 69 תל אביב
שדרות לוי אשכול 71 תל אביב
שדרות לוי אשכול 75 תל אביב
שדרות לוי אשכול 81 תל אביב
לוינסקי 2 תל אביב
משה קול 13 תל אביב
הגדוד העברי 66 תל אביב
פרזון 11 תל אביב
נחום סוקולוב 61 תל אביב
נחום סוקולוב 63 תל אביב
נחום סוקולוב 67 תל אביב
נחום סוקולוב 73 תל אביב
קורט טוכולסקי 9 תל אביב
דרך השלום 93 תל אביב
שפ"ר 4 תל אביב
מעפילי אגוז 104 תל אביב
אופנהיימר 12 תל אביב
מעון 5 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
שדרות ישראל גורי 58 תל אביב
טור מלכא 18 תל אביב
איסר יהודה אונטרמן 8 תל אביב
יצחק שדה 59 תל אביב
החשמונאים 96 תל אביב

פרישמן 75 תל אביב
עזה 14 תל אביב
שפינוזה 24 תל אביב
יפת 171 תל אביב
מעפילי אגוז 58 תל אביב
וינגייט 1 תל אביב
וינגייט 3 תל אביב
וינגייט 7 תל אביב
וינגייט 13 תל אביב
אחרון 15 תל אביב
בני אפרים 280 תל אביב
רפידים 20 תל אביב
אליעזר קפלן 19 תל אביב
אליעזר קפלן 21 תל אביב
אליעזר קפלן 25 תל אביב
אליעזר קפלן 31 תל אביב
שדרות לוי אשכול 118 תל אביב
שדרות לוי אשכול 120 תל אביב
שדרות לוי אשכול 124 תל אביב
שדרות לוי אשכול 130 תל אביב
כורזים 13 תל אביב
שילה 8 תל אביב
הגיבור האלמוני 46 תל אביב
אלכסנדר פן 6 תל אביב
וינגייט 4 תל אביב
דרך הטייסים 86 תל אביב
משעול יעקב 1 תל אביב
קהילת קנדה 45 תל אביב
מעפילי אגוז 73 תל אביב
ויטל 25 תל אביב
יוסף פעמוני 8 תל אביב
חנה אורלוף 3 תל אביב
מוסינזון 21 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
וינגייט 1 תל אביב
וינגייט 3 תל אביב
וינגייט 7 תל אביב
וינגייט 13 תל אביב
ארנון 14 תל אביב
וייצמן 32 תל אביב
עזה 52 תל אביב
הרב יצחק ידידיה פרנקל 75 תל אביב
הרב יצחק ידידיה פרנקל 77 תל אביב
הרב יצחק ידידיה פרנקל 81 תל אביב
הרב יצחק ידידיה פרנקל 87 תל אביב
וולפסון 52 תל אביב
וינגייט 5 תל אביב
וינגייט 7 תל אביב
וינגייט 11 תל אביב
וינגייט 17 תל אביב
מעפילי אגוז 86 תל אביב
אפטר 12 תל אביב
אייגר 10 תל אביב
מיכלאנג'לו 2 תל אביב
מיכלאנג'לו 4 תל אביב
מיכלאנג'לו 8 תל אביב
מיכלאנג'לו 14 תל אביב
החשמונאים 100 תל אביב
ליאונרדו דה וינצ'י 12 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 18 תל אביב
ליאונרדו דה וינצ'י 24 תל אביב
אברהם בויאר 1 תל אביב
הירקון 47 תל אביב
שדרות לוי אשכול 4 תל אביב
שדרות לוי אשכול 6 תל אביב
שדרות לוי אשכול 10 תל אביב
שדרות לוי אשכול 16 תל אביב
שתולים 55 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 8 תל אביב
גרציאני יצחק 12 תל אביב
גרציאני יצחק 18 תל אביב
אילת 38 תל אביב
קורדוברו 14 תל אביב
דוד ילין 16 תל אביב
פוריה 1 תל אביב
הדר יוסף 24 תל אביב
הרב צירלסון 9 תל אביב
דרך שלמה 54 תל אביב
החבצלת 19 תל אביב
נחל הבשור 3 תל אביב
יוניצמן 2 תל אביב
דבורה הנביאה 6 תל אביב
דבורה הנביאה 8 תל אביב
הרב ניסים 9 תל אביב
הרב ניסים 11 תל אביב
משגב עם 12 תל אביב
שתולים 100 תל אביב
שתולים 102 תל אביב
שתולים 106 תל אביב
שתולים 112 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 8 תל אביב
גרציאני יצחק 12 תל אביב
גרציאני יצחק 18 תל אביב
דיק 5 תל אביב
אביגדור סטימצקי 10 תל אביב
שדרות לוי אשכול 2 תל אביב
שדרות לוי אשכול 4 תל אביב
שדרות לוי אשכול 8 תל אביב
שדרות לוי אשכול 14 תל אביב
דרך משה דיין 105 תל אביב
שדרות הר ציון 10 תל אביב
חזנוביץ' 10 תל אביב
חזנוביץ' 12 תל אביב
חזנוביץ' 16 תל אביב
חזנוביץ' 22 תל אביב
הפלמ"ח 17 תל אביב
אמיל זולא 20 תל אביב
שיינקין 57 תל אביב
שיינקין 59 תל אביב
החשמונאים 100 תל אביב
רמז 36 תל אביב
אוסוולדו ארניה 10 תל אביב
אוסוולדו ארניה 12 תל אביב
אוסוולדו ארניה 16 תל אביב
אוסוולדו ארניה 22 תל אביב
הגיבור האלמוני 23 תל אביב
מנחם ארבר 28 תל אביב
גבעת בן יהודה 8 תל אביב
ליאונרדו דה וינצ'י 12 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 18 תל אביב
ליאונרדו דה וינצ'י 24 תל אביב
עמינדב 16 תל אביב
שתולים 59 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 8 תל אביב
גרציאני יצחק 12 תל אביב
גרציאני יצחק 18 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 8 תל אביב
גרציאני יצחק 12 תל אביב
גרציאני יצחק 18 תל אביב
ז'אן ז'ורס 8 תל אביב
אוסוולדו ארניה 16 תל אביב
אוסוולדו ארניה 18 תל אביב
אוסוולדו ארניה 22 תל אביב
אוסוולדו ארניה 28 תל אביב
אשרמן 19 תל אביב
משה שרת 22 תל אביב
סומקן 32 תל אביב
חפר 5 תל אביב
אושה 11 תל אביב
לה גווארדיה 31 תל אביב
המלך ג'ורג' 81 תל אביב
בזל 21 תל אביב
טירת צבי 6 תל אביב
שטרוק 2 תל אביב
מחרוזת 13 תל אביב
פלורנטין 46 תל אביב
בלקינד 1 תל אביב
חנה זמר 15 תל אביב
גונן 12 תל אביב
גונן 14 תל אביב
גונן 18 תל אביב
גונן 24 תל אביב
שדרות ירושלים 3 תל אביב
דבורה הנביאה 13 תל אביב
מחרוזת 14 תל אביב
ניסים אלוני 2 תל אביב
מאפו 20 תל אביב
ניסים אלוני 17 תל אביב
פין 5 תל אביב
פרישמן 69 תל אביב
יוסף האפרתי 7 תל אביב
אמזלג 24 תל אביב
מעפילי אגוז 1 תל אביב
דרך מנחם בגין 144 תל אביב
יצחק אלחנן 15 תל אביב
החשמונאים 96 תל אביב
שתולים 100 תל אביב
שתולים 102 תל אביב
שתולים 106 תל אביב
שתולים 112 תל אביב
קמינסקה 24 תל אביב
ד"ר אברהם אליהו הרכבי 9 תל אביב
ד"ר אברהם אליהו הרכבי 11 תל אביב
ד"ר אברהם אליהו הרכבי 15 תל אביב
ד"ר אברהם אליהו הרכבי 21 תל אביב
ניסים אלוני 2 תל אביב
החשמונאים 96 תל אביב
גיתית 5 תל אביב
מטלון 66 תל אביב
שלומציון המלכה 42 תל אביב
עמנואל הרומי 11 תל אביב
עמנואל הרומי 13 תל אביב
דרך משה דיין 18 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
מעפילי אגוז 84 תל אביב
שדרות חכמי לובלין 6 תל אביב
שדרות חכמי לובלין 8 תל אביב
שדרות חכמי לובלין 12 תל אביב
שדרות חכמי לובלין 18 תל אביב
לסקוב 12 תל אביב
בושם 64 תל אביב
נווה שאנן 39 תל אביב
נווה שאנן 41 תל אביב
נווה שאנן 45 תל אביב
נווה שאנן 51 תל אביב
חברון 12 תל אביב
מאוריציו ויטלה 3 תל אביב
ברוך קרוא 22 תל אביב
אסתר המלכה 1 תל אביב
הרב אהרונסון 20 תל אביב
הרב אהרונסון 22 תל אביב
הרב אהרונסון 26 תל אביב
הרב אהרונסון 32 תל אביב
ליאונרדו דה וינצ'י 11 תל אביב
רודנסקי 8 תל אביב
עין גדי 1 תל אביב
עין גדי 3 תל אביב
מיכאל נאמן 8 תל אביב
בלפור 8 תל אביב
שתולים 24 תל אביב
הקונגרס 6 תל אביב
הקונגרס 8 תל אביב
הקונגרס 12 תל אביב
הקונגרס 18 תל אביב
אבן גבירול 173 תל אביב
לה גווארדיה 33 תל אביב
גרשון ש"ץ 34 תל אביב
ליאונרדו דה וינצ'י 12 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 18 תל אביב
ליאונרדו דה וינצ'י 24 תל אביב
יהודה הימית 61 תל אביב
שדרות ששת הימים 30 תל אביב
מסילת ישרים 56 תל אביב
לוין קיפניס 3 תל אביב
הדסה 6 תל אביב
שדרות לוי אשכול 114 תל אביב
שדרות לוי אשכול 116 תל אביב
שדרות לוי אשכול 120 תל אביב
שדרות לוי אשכול 126 תל אביב
דרך השלום 77 תל אביב
שדרות יד לבנים 23 תל אביב
שמריהו לוין 13 תל אביב
וולפסון 52 תל אביב
רמה 2 תל אביב
השל"ה 1 תל אביב
בורוכוב 8 תל אביב
בורוכוב 10 תל אביב
בורוכוב 14 תל אביב
ז'בוטינסקי 91 תל אביב
יהודה המכבי 49 תל אביב
מעפילי אגוז 66 תל אביב
היהודי זיס 10 תל אביב
כ"ג יורדי הסירה 1 תל אביב
החשמונאים 100 תל אביב
אחד העם 100 תל אביב
אחד העם 102 תל אביב
אחד העם 106 תל אביב
האקליפטוס 6 תל אביב
מנדלי מוכר ספרים 14 תל אביב
הרב רובינשטיין 21 תל אביב
הרב רובינשטיין 23 תל אביב
הרב רובינשטיין 27 תל אביב
הרב רובינשטיין 33 תל אביב
הפרטיזן היהודי 31 תל אביב
אחד העם 47 תל אביב
משה וילנסקי 55 תל אביב
שילה 8 תל אביב
אלתרמן 7 תל אביב
פילדלפיה 9 תל אביב
יפתח 3 תל אביב
יוניצמן 21 תל אביב
יוניצמן 23 תל אביב
יוניצמן 27 תל אביב
יוניצמן 33 תל אביב
הנביאים 15 תל אביב
פרץ חיות 2 תל אביב
פרץ חיות 4 תל אביב
פרץ חיות 8 תל אביב
פרץ חיות 14 תל אביב
עמק ברכה 26 תל אביב
התנאים 9 תל אביב
ענתות 35 תל אביב
קהילת קנדה 20 תל אביב
אייגר 14 תל אביב
קדם 75 תל אביב
ברודצקי 27 תל אביב
הבלונים / 3695  1 תל אביב
הבלונים / 3695  3 תל אביב
הבלונים / 3695  7 תל אביב
הבלונים / 3695  13 תל אביב
יהושע בן נון 45 תל אביב
החשמונאים 96 תל אביב
דיזנגוף 269 תל אביב
חזנוביץ' 10 תל אביב
חזנוביץ' 12 תל אביב
חזנוביץ' 16 תל אביב
חזנוביץ' 22 תל אביב
בעל הטורים 4 תל אביב
יחיאל דב דרזנר 12 תל אביב
אורי צבי גרינברג 5 תל אביב
פנקס 66 תל אביב
הקלעים 7 תל אביב
סומקן 10 תל אביב
שתולים 61 תל אביב
רמז 16 תל אביב
נחום הנביא 27 תל אביב
נחום הנביא 29 תל אביב
נחום הנביא 33 תל אביב
נחום הנביא 39 תל אביב
חיים בן עטר 12 תל אביב
חיים בן עטר 14 תל אביב
חיים בן עטר 18 תל אביב
חיים בן עטר 24 תל אביב
שתולים 57 תל אביב
בן שפרוט 2 תל אביב
החבצלת 18 תל אביב
מח"ל 72 תל אביב
נחמני 53 תל אביב
נחמני 55 תל אביב
נחמני 59 תל אביב
נחמני 65 תל אביב
דרך חיים ברלב 149 תל אביב
אח"י דקר 4 תל אביב
אח"י דקר 6 תל אביב
אח"י דקר 10 תל אביב
מקראי קדש 15 תל אביב
ארלוזורוב 17 תל אביב
ארלוזורוב 19 תל אביב
שילה 5 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
סלסלה 8 תל אביב
סלסלה 10 תל אביב
סלסלה 14 תל אביב
סלסלה 20 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
יינון 6 תל אביב
לה גווארדיה 64 תל אביב
תשבי 11 תל אביב
י.ל. פרץ 4 תל אביב
י.ל. פרץ 6 תל אביב
י.ל. פרץ 10 תל אביב
י.ל. פרץ 16 תל אביב
קהילת ורשה 65 תל אביב
דוד אבידן 13 תל אביב
יסוד המעלה 47 תל אביב
הבלונים / 3695 1 תל אביב
הבלונים / 3695 3 תל אביב
הבלונים / 3695 7 תל אביב
הבלונים / 3695 13 תל אביב
החשמונאים 96 תל אביב
שפ"ר 4 תל אביב
פאת השולחן 14 תל אביב
בוגרשוב 68 תל אביב
הגיחון 8 תל אביב
דרך משה דיין 36 תל אביב
דרך משה דיין 38 תל אביב
דרך משה דיין 42 תל אביב
לוין קיפניס 1 תל אביב
פין 1 תל אביב
זריצקי 7 תל אביב
דרך הטייסים 104 תל אביב
דרך הטייסים 106 תל אביב
דרך הטייסים 110 תל אביב
רציף הרברט סמואל 46 תל אביב
ניסים אלוני 1 תל אביב
אמיר גלבוע 21 תל אביב
אמיר גלבוע 23 תל אביב
אמיר גלבוע 27 תל אביב
אמיר גלבוע 33 תל אביב

הכנסת הגדולה 15 תל אביב
הקונגרס 9 תל אביב
קמינסקה 12 תל אביב
איסרליש 14 תל אביב
יצחק שדה 52 תל אביב
בן חיל 9 תל אביב
איסר יהודה אונטרמן 42 תל אביב
יונה הנביא 38 תל אביב
שדרות ישראל גורי 52 תל אביב
מזא"ה 74 תל אביב
מזא"ה 76 תל אביב
מזא"ה 80 תל אביב
מזא"ה 86 תל אביב
בני אפרים 244 תל אביב
פיקוס 3 תל אביב
מעפילי סלוודור 7 תל אביב
מעפילי סלוודור 9 תל אביב
מעפילי סלוודור 13 תל אביב
מעפילי סלוודור 19 תל אביב
מנדלי מוכר ספרים 14 תל אביב
מאיר יערי 4 תל אביב
הירקון 254 תל אביב
נחמני 35 תל אביב
חנוך 4 תל אביב
אופנהיימר 12 תל אביב
מרים החשמונאית 14 תל אביב
דרך מנחם בגין 144 תל אביב
קורקידי 20 תל אביב
מעפילי אגוז 1 תל אביב
ליאונרדו דה וינצ'י 12 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
ליאונרדו דה וינצ'י 18 תל אביב
ליאונרדו דה וינצ'י 24 תל אביב
דוד אבידן 13 תל אביב
קלמן 20 תל אביב
פיקוס 27 תל אביב
בבלי 18 תל אביב
עמק ברכה 34 תל אביב
החבצלת 19 תל אביב
שטיינברג 1 תל אביב
אלנבי 69 תל אביב
כהנשטם 2 תל אביב
שדרות וושינגטון 24 תל אביב
נחום סוקולוב 97 תל אביב
נחום סוקולוב 99 תל אביב
נחום סוקולוב 103 תל אביב
נחום סוקולוב 109 תל אביב
יהודה הימית 25 תל אביב
דבורה הנביאה 13 תל אביב
שדרות יד לבנים 23 תל אביב
יוסף קארו 27 תל אביב
מאיר יערי 20 תל אביב
מחרוזת 7 תל אביב
גדעון 10 תל אביב
דרך השלום 79 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 8 תל אביב
גרציאני יצחק 12 תל אביב
גרציאני יצחק 18 תל אביב
הגר"א 39 תל אביב
בנבנישתי 12 תל אביב
גרציאני יצחק 6 תל אביב
גרציאני יצחק 8 תל אביב
גרציאני יצחק 12 תל אביב
גרציאני יצחק 18 תל אביב
טרומפלדור 48 תל אביב
התנאים 16 תל אביב
אליהו בית צורי 14 תל אביב
אליהו חכים 16 תל אביב
נחליאל 24 תל אביב
הכינור 1 תל אביב
זלמן שז"ר 1 תל אביב
זלמן שז"ר 3 תל אביב
זלמן שז"ר 7 תל אביב
ארלוזורוב 156 תל אביב
לה גווארדיה 64 תל אביב
בן סרוק 26 תל אביב
ליאונרדו דה וינצ'י 2 תל אביב
ליאונרדו דה וינצ'י 4 תל אביב
ליאונרדו דה וינצ'י 8 תל אביב
ליאונרדו דה וינצ'י 14 תל אביב
בית אל 21 תל אביב
בית אל 23 תל אביב
בית אל 27 תל אביב
בית אל 33 תל אביב
ברנר 6 תל אביב
בבלי 43 תל אביב
קמינסקה 22 תל אביב
אלנבי 138 תל אביב
אלנבי 140 תל אביב
אלנבי 144 תל אביב
אלנבי 150 תל אביב
יפת 171 תל אביב
יפתח 18 תל אביב
מרכז בעלי מלאכה 40 תל אביב
בן סרוק 26 תל אביב
צידון 7 תל אביב
מח"ל 80 תל אביב
י.ל. פרץ 42 תל אביב
י.ל. פרץ 44 תל אביב
י.ל. פרץ 48 תל אביב
י.ל. פרץ 54 תל אביב
יפת 181 תל אביב
אייזק שטרן 13 תל אביב
מנחם ארבר 31 תל אביב
ישראליס 22 תל אביב
קדם 169 תל אביב
לוחמי גליפולי 19 תל אביב
בני אפרים 280 תל אביב
סר ג'ון מונש 15 תל אביב
סר ג'ון מונש 17 תל אביב
סר ג'ון מונש 21 תל אביב
סר ג'ון מונש 27 תל אביב
מעפילי אגוז 28 תל אביב
מעפילי אגוז 30 תל אביב
מעפילי אגוז 34 תל אביב
מעפילי אגוז 40 תל אביב
נחלת בנימין 133 תל אביב
קהילת לודז' 44 תל אביב
קהילת לודז' 46 תל אביב
קהילת לודז' 50 תל אביב
קהילת לודז' 56 תל אביב
דרך מנחם בגין 158 תל אביב
דרך מנחם בגין 160 תל אביב
דרך מנחם בגין 164 תל אביב
דרך מנחם בגין 170 תל אביב
דיזנגוף 212 תל אביב
אלכסנדר סשה ארגוב 62 תל אביב
אלכסנדר סשה ארגוב 64 תל אביב
אלכסנדר סשה ארגוב 68 תל אביב
אלכסנדר סשה ארגוב 74 תל אביב
צהלון הרופא 3 תל אביב
החשמונאים 75 תל אביב
צבי פרידלנד 1 תל אביב
שדרות לוי אשכול 106 תל אביב
שדרות לוי אשכול 108 תל אביב
שדרות לוי אשכול 112 תל אביב
שדרות לוי אשכול 118 תל אביב
ניסים אלוני 2 תל אביב
יוניצמן 21 תל אביב
יוניצמן 23 תל אביב
יוניצמן 27 תל אביב
יוניצמן 33 תל אביב
הרכבת 16 תל אביב
קהילת לבוב 9 תל אביב
דרך ההגנה 140 תל אביב
בילטמור 6 תל אביב
סימני דרך 62 תל אביב
סימני דרך 64 תל אביב
סימני דרך 68 תל אביב
סימני דרך 74 תל אביב
הר נבו 4 תל אביב
בן יהודה 48 תל אביב
הפרדסים 6 תל אביב
הפרדסים 8 תל אביב
הפרדסים 12 תל אביב
הפרדסים 18 תל אביב
צופית 2 תל אביב
צופית 4 תל אביב
צופית 8 תל אביב
צופית 14 תל אביב
דרך ארץ 1 תל אביב
דרך ארץ 3 תל אביב
דרך ארץ 7 תל אביב
דרך ארץ 13 תל אביב
קהילת קנדה 39 תל אביב
אברהם לינקולן 2 תל אביב
אברהם לינקולן 4 תל אביב
אברהם לינקולן 8 תל אביב
אברהם לינקולן 14 תל אביב
אסתר המלכה 88 תל אביב
אסתר המלכה 90 תל אביב
אסתר המלכה 94 תל אביב
אסתר המלכה 100 תל אביב
1477
1478
1637
shape (1637, 42)
(0, 42)

C:\Users\yoavl\anaconda3\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

In [83]:
df = df.drop(columns=['Balconies','Parking','Balconies','Immediate'
                      ,'Ac','Furniture','On_pillars','Elevator','Storeroom','Shelter',
                     'Text','Date_of_entry','Images','Handicapped','Floors_text','Agency', 'Garden_size' 
                      , 'Date_added', 'City_code','City'], axis=1)


def update_asset_conditon(df):
    '''
    1- new from builder
    2 - new 
    3 - good
    4 - after reinovtions 
    5 - need reinovtions
    '''
    df.rename(columns = {'Asset_classification':'Condition'}, inplace = True)
    df['Condition'] = df['Condition'].astype(np.int32)
    df.loc[df['Condition'] == 2, 'Condition'] = 4 
    df.loc[df['Condition'] == 6, 'Condition'] = 2
    
    return df
    
def update_neighborhood_street(df):
    df['Street'] = df['Street'].str.strip()
    old = "'"
    new = ''
    df['Street'] = df['Street'].str.replace(old,new)
    df['Neighborhood'] = df['Neighborhood'].str.replace(old,new)
    
    old = 'כרמייה'
    new = 'כרמיה'
    df['Street'] = df['Street'].str.replace(old,new)

    df['Neighborhood'] = df['Neighborhood'].str.strip()
    old = '-'
    new = ' '
    df['Neighborhood'] = df['Neighborhood'].str.replace(old,new)
    old = 'נווה אביבים'
    new = 'נווה אביבים וסביבתה'
    df['Neighborhood'] = df['Neighborhood'].str.replace(old,new)
    df['Neighborhood'] = df['Neighborhood'].str.replace('לב תל אביב, לב העיר צפון','הצפון הישן החלק הצפוני')
    df['Neighborhood'] = df['Neighborhood'].str.replace('נוה','נווה')
    df['Neighborhood'] = df['Neighborhood'].str.replace('גני צהלה, רמות צהלה','גני צהלה')
    df['Neighborhood'] = df['Neighborhood'].str.replace('נווה אליעזר וכפר שלם מזרח','כפר שלם מזרח נווה אליעזר')
    df['Neighborhood'] = df['Neighborhood'].str.replace('גני שרונה, קרית הממשלה','גני שרונה')
    old = 'הצפון הישן   דרום'
    new = 'הצפון החדש החלק הדרומי'
    df['Neighborhood'] = df['Neighborhood'].str.replace(old,new)
    df['Neighborhood'] = df['Neighborhood'].str.replace('מכללת תל אביב יפו, דקר','דקר')

    return df
 
    
df = update_asset_conditon(df)
df = update_neighborhood_street(df)

Empty DataFrame
Columns: [Price, Street, Neighborhood, Size, Floors, Condition, Street_id, Rooms, Floor, Lat, Long, Neighborhood_id, Home_number, Item_id, Asset_type, Broker, Accuracy, Date, Last_update, Valid, Gush, Helka, Tat]
Index: []

[0 rows x 23 columns]

In [84]:
def convert_coordinates(lat_long_list):
    '''
    This function use to convert UTM coordinates to ITM coordinates using outside website with selenium 
    '''
    service = Service("C:/Users/yoavl/NextRoof/chromedriver_win32/chromedriver.exe")
    driver = webdriver.Chrome(service=service)
    driver.get("https://zvikabenhaim.appspot.com/software/ITM/")

    # locate all the input fields and button
    lat_input = driver.find_element(By.XPATH, '//*[@id="lat"]')
    lon_input = driver.find_element(By.XPATH, '//*[@id="long"]')
    convert_button = driver.find_element(By.XPATH, '//form[1]/table/tbody/tr[3]/td/input')
    east_span = driver.find_element(By.XPATH, '//*[@id="itm_east"]')
    north_span = driver.find_element(By.XPATH, '//*[@id="itm_north"]')
    
    
    coverted_list = []
    for cords in lat_long_list:
        east = cords[0]
        north = cords[1]
        if cords[0] != 0.0 and cords[1] != 0.0:
            lat_input.clear()
            lon_input.clear()

            # send lat and long to input fields

            lat_input.send_keys(cords[0])
            lon_input.send_keys(cords[1])

            convert_button.click()


            east = east_span.text
            north = north_span.text
            
            
        coverted_list.append((east,north))
        

    driver.quit()
    return coverted_list

def convert_lat_long(df):

    def get_long_lat_tuples(df):
        long_lat_tuples = []
        for index, row in df.iterrows():
            lat = row['Lat']
            long = row['Long']

            try:
                lat = float(lat)
            except:
                lat = 0.0
            try:
                long = float(long)
            except:
                long = 0.0
                
            long_lat_tuples.append((lat, long))


        return long_lat_tuples
    
    new_cord = convert_coordinates(get_long_lat_tuples(df))
    
    for index, row in df.iterrows():  
        try:
            df.at[index,'Lat'] = new_cord[index][0]
            df.at[index,'Long'] = new_cord[index][1]
        except:
            pass


    return df

In [85]:
def find_avg_cords_by_street():
    df = pd.read_csv("Data/Nadlan_clean.csv",index_col=0)
    df = df.dropna(subset=['Long','Lat','Street']).reset_index(drop=True)
    df['Long'] = df['Long'].astype(int)
    df['Lat'] = df['Lat'].astype(int)
    
    # create unique streets list
    streets = df['Street'].unique()
    
    street_cords_avg = {}
    for street in streets:
        street_df = df[df['Street'] == street]
        
        lat_mean = street_df['Lat'].mean()
        long_mean = street_df['Long'].mean()

        street_cords_avg[street] = (long_mean ,lat_mean)
        
    return street_cords_avg
        
def complete_long_lat_columns(df,street_cords_avg):
    for index, row in df.iterrows():
        long = row['Long']
        lat = row['Lat']
        street = row['Street']
        
        try:
            cords = street_cords_avg[street]         
            if long == 0.0 or lat == 0.0:
                df.at[index, 'Long'] = cords[1]
                df.at[index, 'Lat'] = cords[0]

                
        except:
            pass

    
    df.rename(columns = {'Lat':'Temp'}, inplace = True)
    df.rename(columns = {'Long':'Lat'}, inplace = True)
    df.rename(columns = {'Temp':'Long'}, inplace = True)

    df = df.loc[(df['Lat'] != 0.0) & (df['Long'] != 0.0)]
    
    df.loc[:, 'Long'] = df['Long'].astype(np.int32)
    df.loc[:, 'Lat'] = df['Lat'].astype(np.int32)
    
    return df
            
df = convert_lat_long(df)
df =complete_long_lat_columns(df,find_avg_cords_by_street())
df

C:\Users\yoavl\anaconda3\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

,Price,Street,Neighborhood,Size,Floors,Condition,Street_id,Rooms,Floor,Long,...,Item_id,Asset_type,Broker,Accuracy,Date,Last_update,Valid,Gush,Helka,Tat
5,"5,800,000 ₪",דוד אבידן,המשתלה,148.0,8.0,5,4781.0,6.0,1.0,179100,...,9qe2e0by,‫דירות,False,90,NaN,NaN,NaN,6615,304,NaN
7,"3,300,000 ₪",יוחנן הורקנוס,הצפון הישן צפון,44.0,3.0,3,420.0,1.0,1.0,179481,...,bpvgxamv,‫דירות,False,100,NaN,NaN,NaN,6958,110,NaN
15,"38,000,000 ₪",רציף הרברט סמואל,NaN,180.0,10.0,2,1143.0,4.0,5.0,178011,...,kkksfluv,דירה,True,80,NaN,NaN,NaN,6916,120,NaN
20,"2,670,000 ₪",שקד,"נווה עופר, תל כביר",65.0,4.0,4,3010.0,3.0,1.0,181168,...,malzmipg,דירה,False,100,2023-06-19,עודכן ב 03/07/2023,NaN,6993,121,NaN
25,"3,200,000 ₪",שיבת ציון,נווה שאנן,80.0,3.0,3,2324.0,3.0,1.0,181217,...,mb12abmw,‫דירות,False,100,2023-04-12,עודכן היום,NaN,6975,68,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5766,"3,650,000 ₪",בן יהודה,הצפון החדש החלק הדרומי,55.0,3.0,3,510.0,2.0,2.0,178556,...,1wg5yqum,NaN,NaN,80,2023-07-17,עודכן ב 17/07/2023,1.0,6906,152,NaN
5770,"2,750,000 ₪",צופית,חלומות זכרון,112.0,5.0,2,283.0,4.0,3.0,32,...,oxvzdapo,NaN,NaN,100,2023-07-08,עודכן היום,1.0,7028,78,NaN
5771,"2,055,000 ₪",דרך ארץ,עיר היין,123.0,17.0,1,1210.0,4.0,16.0,31,...,lqmhne24,NaN,NaN,100,2023-07-12,עודכן היום,1.0,6623,946,NaN
5772,"1,750,000 ₪",קהילת קנדה,"יפו ד, גבעת התמרים",49.0,4.0,3,2199.0,2.0,1.0,176800,...,45lpdtq5,NaN,NaN,90,2022-12-16,עודכן היום,1.0,7050,177,NaN
5774,"2,250,000 ₪",אברהם לינקולן,אחוזה,180.0,6.0,4,593.0,4.0,2.0,32,...,wnipas8b,NaN,NaN,100,2023-07-16,עודכן היום,1.0,7103,88,NaN

In [86]:
df = df.dropna(subset=['Street']).reset_index(drop=True)
print(df.shape)
# (2464, 18)

(1232, 23)

In [87]:
def add_neighborhood():
    df = pd.read_csv("Data/Real_Estate_TLV_GOVMAPS_1.csv",index_col=0)
    neighborhoods = {}
    for index, row in df.iterrows():
        neighborhood = row['NEIGHBORHOOD']
        street = row['STREENNAME']
        if neighborhood not in neighborhoods:
            neighborhoods[neighborhood] = set()
        neighborhoods[neighborhood].add(street)
    return neighborhoods

def complete_neighborhood_column(df, neighborhoods):
    # Loop through each row in the DataFrame
    for index, row in df.iterrows():
        street = row['Street']
        
        # Loop through each neighborhood in the neighborhoods dictionary
        for neighborhood, streets in neighborhoods.items():
            # Check if the street is in the set of streets for the neighborhood
            if street in streets:
                # If it is, assign the neighborhood to the 'neighborhood' column for this row
                df.at[index, 'Neighborhood'] = neighborhood
                break # Break out of the inner loop once we find a match
    
    return df

df = complete_neighborhood_column(df,add_neighborhood())

In [88]:
def create_building_year_list():
    df = pd.read_csv("Data/Nadlan_clean.csv",index_col=0)
    df = df.dropna(subset=['Floors','Street','Build_year']).reset_index(drop=True)
    
    add_build_year = []
    df['Floors'] = df['Floors'].astype(int)
    df['Street'] = df['Street'].astype(str)
    df['Build_year'] = df['Build_year'].astype(int)
    
    for index, row in df.iterrows():
        floors = row['Floors']
        street = row['Street']
        build_year = row['Build_year']
        
        build_string = (str(floors)+str(street)+str(build_year)).strip()
        
        add_build_year.append(build_string)
    return list(set(add_build_year))

def complete_build_year_column(df, add_build_year):
    df['Build_year'] = 0
    df['Floors'] = df['Floors'].fillna(0)
    
    df['Floors'] = df['Floors'].astype(int)
    df['Street'] = df['Street'].astype(str)
    
    # Loop through each row in the DataFrame
    for index, row in df.iterrows():
        floors = row['Floors']
        street = row['Street']
        build_year = row['Build_year']

        build_string = (str(floors)+str(street)).strip().strip()

        for item in add_build_year:
            floors_street_year = item.strip()
            
            if floors_street_year.startswith(build_string):
                year = floors_street_year[-4:]
                year = re.findall(r'\d+', year)
                year = ''.join(year)
                df.at[index,'Build_year'] = year
                break

    return df

In [89]:
def find_avg_building_old_by_street():
    
    df = pd.read_csv("Data/Nadlan_clean.csv",index_col=0)
    df = df.dropna(subset=['Build_year','Street']).reset_index(drop=True)
    df['Build_year'] = df['Build_year'].astype(int)
    df['Street'] = df['Street'].astype(str)
    
    # create unique streets list
    streets = df['Street'].unique()
    
    street_buildings_avg = {}
    for street in streets:
        
        street_df = df[df['Street'] == street]
        street_mean = street_df['Build_year'].mean()
        
        
        street_buildings_avg[street] = street_mean
        
    return street_buildings_avg
        
def complete_building_old_by_street(df,avg_bulding_old_street):
    for index, row in df.iterrows():
        old = row['Build_year']
        street = row['Street']
        if old == 0:
            try:
                avg = avg_bulding_old_street[street] 
                df.at[index, 'Build_year'] = avg
            except:
                df.drop(index = index , inplace =True)
            
            
        
    df['Build_year'] = df['Build_year'].astype(np.int32)

    return df

df = complete_build_year_column(df,create_building_year_list())

df = complete_building_old_by_street(df,find_avg_building_old_by_street())

In [90]:
def calc_distance_from_the_see_TLV(X_coordinate, Y_coordinate):
    north_x = 180471
    north_y = 672391
    south_x = 177333
    south_y = 663016
    
    m = (south_y - north_y) / (south_x - north_x)   
    b = north_y - (m * north_x)
    
    numerator = abs(m * X_coordinate - Y_coordinate + b)
    denominator = math.sqrt(m**2 + 1)
    return numerator / denominator


def calc_distance_from_train_station(df):
    stations = [(179820.47,662424.54), (180619,664469.56), (181101.44,665688.78), (181710.96,667877.05)]
    distances = []

     # Iterate over each row in the DataFrame
    for index, row in df.iterrows():
        apartment_coords = (row['Lat'], row['Long'])

        # Calculate the distance between the apartment and each train station
        station_distances = []
        for station_coords in stations:       
            station_distance = abs(station_coords[0] - apartment_coords[1]) + abs(station_coords[1] - apartment_coords[0])
            station_distances.append(station_distance)

        # Find the minimum distance
        min_distance = min(station_distances)
        distances.append(min_distance)

    df['Train'] = distances
    df['Train'] = df['Train'].astype(np.int32)
    return df
    
def distance_from_sea_tlv(df):
    '''
    Need to fix long ? lat ? 
    '''
    df = df.dropna(subset=['Lat', 'Long']).reset_index(drop=True)
    latitudes = df['Long'].astype(float)
    longitudes = df['Lat'].astype(float)
    distances = [calc_distance_from_the_see_TLV(lat, lon) for lat, lon in zip(latitudes, longitudes)]
    df['Distance_sea'] = distances
    df['Distance_sea'] = df['Distance_sea'].astype(np.int32)
    return df

In [91]:
def edit_parking(df):
    # Not in use
    df['Parking'] = df['Parking'].str.replace('ללא','0')
    df['Parking'] = df['Parking'].astype(np.int32)
    return df

    
def add_date(df):
    # all the deals need to be 2023
    df['Year'] = 2023
    df.assign(profit='NAN')
    df['Year'].astype(np.int32)
    return df

def convert_price(df):
    df['Price'] = df['Price'].str.replace('לא צוין מחיר', '0')
    df['Price'] = df['Price'].str.replace('₪', '')
    df['Price'] = df['Price'].str.replace(',', '')
    df['Price'] = df['Price'].astype(np.int32)

    return df



def street_and_neighborhood_rank(df, column):
    df = update_neighborhood_street(df)
    df = df.dropna(subset=['Neighborhood','Street']).reset_index(drop=True)
    df_nadlan = pd.read_csv('Data/Nadlan_clean.csv', index_col=0)

        
    streets_rank = {}
    years = df_nadlan['Year'].unique()

    for year in years:
        df_by_year = df_nadlan[df_nadlan['Year'] == year]
        streets_rank[year] = {}

        for item in df_by_year[column].unique():
            df_by_item = df_by_year[df_by_year[column] == item]  # Filter df by item
            
            item_year_rank = np.nan
            if df_by_item['Size'].sum() != 0:
                item_year_rank = df_by_item['Price'].sum() / df_by_item['Size'].sum()

            streets_rank[year][item] = item_year_rank

    new_column_name = column + '_rank'
    df[new_column_name] = np.nan

    for index, row in df.iterrows():
        year = row['Year']
        item = row[column]
        found_street = False

        # Check for exact matches
        for nadlan_street in df_nadlan[column].unique():
            if item == nadlan_street:
                found_street = True
                item = nadlan_street
                break

        # Check for partial matches
        if not found_street and  found_street != False:
            for nadlan_street in df_nadlan[column].unique():
                if item in nadlan_street:
                    item = nadlan_street
                    found_street = True
                    break
                    
                check_parts = nadlan_street.split(' ')
                print(check_parts)
                if item in check_parts:
                    item = nadlan_street
                    found_street = True
                    break

        if found_street:
            for potential_year in [year, year-1, year-2 , year-3]:
                try:
                    df.at[index, new_column_name] = streets_rank[potential_year][item]
                    break
                except KeyError:
                    continue
                    
                    
        else:
            pass
#             print(f"Could not find a match for {column} '{item}'")
            
    mean = df[new_column_name].mean()
    df[new_column_name] = df[new_column_name].fillna(mean)
    df[new_column_name] = df[new_column_name].astype(np.int32)
    return df

In [92]:
df = convert_price(df)
df = distance_from_sea_tlv(df)
df = calc_distance_from_train_station(df)
df = add_date(df)
df = street_and_neighborhood_rank(df,'Neighborhood')
df = street_and_neighborhood_rank(df,'Street')
df = street_and_neighborhood_rank(df,'Gush')

In [94]:
def check_for_match(df_nadlan, helka, year):
    helka = int(helka)
    helka_offsets = [helka - 1, helka + 1, helka + 2, helka - 2, helka + 3, helka - 3, helka + 4, helka - 4]
    for helka_offset in helka_offsets:
        for year_offset in range(4, 0, -1):
            year_temp = year - year_offset
            match = df_nadlan.loc[(df_nadlan['Gush_Helka'] == str(helka_offset)) & (df_nadlan['Year'] == year_temp), 'Helka_rank']
            if not match.empty:
                return match
    return match


def helka_rank(df):
    count = 0
    df = df.dropna(subset=['Gush','Helka']).reset_index(drop=True)
    df_nadlan = pd.read_csv('Data/Nadlan_clean.csv', index_col=0)
    df_nadlan['Gush_Helka'] = df_nadlan['Gush'].astype(str) + df_nadlan['Helka'].astype(str)
    
    column = 'Gush_Helka'

    df[column] = df['Gush'].astype(str) + df['Helka'].astype(str)
    df[column] = df[column].str.replace('.','')
    
    for index, row in df.iterrows():
        gush_helka = row['Gush_Helka']
        year = 2023
        helka_rank = np.nan
        
        match = df_nadlan.loc[(df_nadlan['Gush_Helka'] == gush_helka) & df_nadlan['Year'] == year  ,'Helka_rank']
        
        if match.empty:
            match = check_for_match(df_nadlan, gush_helka , year)
    
        
        if not match.empty:
            df.at[index, 'Helka_rank'] = match.values[0]
        
        if match.empty:
            count+=1
    mean = df['Helka_rank'].mean()
    df['Helka_rank'] = df['Helka_rank'].fillna(mean)
    df['Helka_rank'] = df['Helka_rank'].astype(np.int32)
    print(count)
    return df



def check_for_match_update(df_nadlan, helka):
    helka = int(helka)
    helka_offsets = [helka - 1, helka + 1, helka + 2, helka - 2, helka + 3, helka - 3, helka + 4, helka - 4]
    for helka_offset in helka_offsets:
        match = df_nadlan.loc[(df_nadlan['Gush_Helka'] == str(helka_offset)), 'Helka_rank']
        if not match.empty:
            return match
    return match

def helka_rank_update(df):
    count = 0
    df = df.dropna(subset=['Gush','Helka']).reset_index(drop=True)
    df_nadlan = pd.read_csv('Data/Nadlan_clean.csv', index_col=0)
    df_nadlan['Gush_Helka'] = df_nadlan['Gush'].astype(str) + df_nadlan['Helka'].astype(str)
    
    column = 'Gush_Helka'

    df[column] = df['Gush'].astype(str) + df['Helka'].astype(str)
    df[column] = df[column].str.replace('.', '', regex=False)
    
    for index, row in df.iterrows():
        gush_helka = row['Gush_Helka']
        helka_rank = np.nan
        
        match = df_nadlan.loc[(df_nadlan['Gush_Helka'] == gush_helka),'Helka_rank']
        
        if match.empty:
            match = check_for_match_update(df_nadlan, gush_helka)
    
        if not match.empty:
            df.at[index, 'Helka_rank'] = match.values[0]
        
        if match.empty:
            count+=1
      
    mean = df['Helka_rank'].mean()
    df['Helka_rank'] = df['Helka_rank'].fillna(mean)
    df['Helka_rank'] = df['Helka_rank'].astype(np.int32)
    print(count)
    return df

In [95]:
df = helka_rank_update(df)
df.to_csv('Data/Yad2_clean.csv',index=False)

65

In [96]:
def append_to_file():
    file_path = "status.txt"
    message = "yad_2_clean pass-success"

    try:
        # Open the file in append mode
        with open(file_path, "a") as file:
            # Append the message on a new line
            file.write("\n" + message)

        print("Message appended to the file successfully!")
    except Exception as e:
        print("An error occurred while appending to the file:", str(e))

# Call the function to append to the file
append_to_file()

Message appended to the file successfully!

In [97]:
df.shape

(1026, 32)